
namespace SiproModelCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the EJECUCION_ESTADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("EJECUCION_ESTADO")]
	public partial class EjecucionEstado
	{
		[Key]
	    public virtual Int64 id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	}
}
