
namespace SiproModelCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO")]
	public partial class Formulario
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual string codigo { get; set; }
	    public virtual string descripcion { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
	    [Column("FORMULARIO_TIPOID")]
	    [ForeignKey("FormularioTipo")]
        public virtual Int32 formularioTipoid { get; set; }
		public virtual FormularioTipo formularioTipos { get; set; }
		public virtual IEnumerable<Formulario> formularios { get; set; }
	}
}
