
namespace SiproModelCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODUCTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRODUCTO_PROPIEDAD_VALOR")]
	public partial class ProductoPropiedadValor
	{
		[Key]
	    [Column("PRODUCTO_PROPIEDADID")]
	    [ForeignKey("ProductoPropiedad")]
        public virtual Int32 productoPropiedadid { get; set; }
		[Key]
	    [ForeignKey("Producto")]
        public virtual Int32 productoid { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual Int32? valorEntero { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual decimal? valorDecimal { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual DateTime? valorTiempo { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
		public virtual ProductoPropiedad productoPropiedads { get; set; }
		public virtual Producto productos { get; set; }
		public virtual IEnumerable<ProductoPropiedadValor> productopropiedadvalors { get; set; }
	}
}
