
namespace SiproModelCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO_PROPIEDAD_VALOR")]
	public partial class ProyectoPropiedadValor
	{
		[Key]
	    [ForeignKey("Proyecto")]
        public virtual Int32 proyectoid { get; set; }
		[Key]
	    [Column("PROYECTO_PROPIEDADID")]
	    [ForeignKey("ProyectoPropiedad")]
        public virtual Int32 proyectoPropiedadid { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual Int32? valorEntero { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual decimal? valorDecimal { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual DateTime? valorTiempo { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual ProyectoPropiedad proyectoPropiedads { get; set; }
		public virtual IEnumerable<ProyectoPropiedadValor> proyectopropiedadvalors { get; set; }
	}
}
