
namespace SiproModelCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PTIPO_PROPIEDAD")]
	public partial class PtipoPropiedad
	{
		[Key]
	    [Column("PROYECTO_TIPOID")]
	    [ForeignKey("ProyectoTipo")]
        public virtual Int32 proyectoTipoid { get; set; }
		[Key]
	    [Column("PROYECTO_PROPIEDADID")]
	    [ForeignKey("ProyectoPropiedad")]
        public virtual Int32 proyectoPropiedadid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32? estado { get; set; }
		public virtual ProyectoTipo proyectoTipos { get; set; }
		public virtual ProyectoPropiedad proyectoPropiedads { get; set; }
		public virtual IEnumerable<PtipoPropiedad> ptipopropiedads { get; set; }
	}
}
