
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ACTIVIDAD_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("actividad_propiedad_valor")]
	public partial class actividad_propiedad_valor
	{
		[Key]
	    [ForeignKey("actividad")]
        public virtual string actividadid { get; set; }
		[Key]
	    [ForeignKey("actividad_propiedad")]
        public virtual string actividad_propiedadid { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual actividad_propiedad actividad_propiedads { get; set; }
		public virtual actividad actividads { get; set; }
		public virtual IEnumerable<actividad_propiedad_valor> actividadpropiedadvalors { get; set; }
	}
}
