
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ACTIVIDAD_USUARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("ACTIVIDAD_USUARIO")]
	public partial class ActividadUsuario
	{
		[Key]
	    [ForeignKey("Actividad")]
        public virtual string actividadid { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual Actividad actividads { get; set; }
		public virtual IEnumerable<ActividadUsuario> actividadusuarios { get; set; }
	}
}
