
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ACTIVIDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("actividad")]
	public partial class actividad
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string fecha_inicio { get; set; }
	    public virtual string fecha_fin { get; set; }
	    public virtual string porcentaje_avance { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("actividad_tipo")]
        public virtual string actividad_tipoid { get; set; }
	    public virtual string snip { get; set; }
	    public virtual string programa { get; set; }
	    public virtual string subprograma { get; set; }
	    public virtual string proyecto { get; set; }
	    public virtual string _actividad { get; set; }
	    public virtual string obra { get; set; }
	    public virtual string objeto_id { get; set; }
	    public virtual string objeto_tipo { get; set; }
	    public virtual string duracion { get; set; }
	    public virtual string duracion_dimension { get; set; }
	    public virtual string pred_objeto_id { get; set; }
	    public virtual string pred_objeto_tipo { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string costo { get; set; }
	    [ForeignKey("acumulacion_costo")]
        public virtual string acumulacion_costo { get; set; }
	    public virtual string renglon { get; set; }
	    public virtual string ubicacion_geografica { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual string nivel { get; set; }
	    public virtual string proyecto_base { get; set; }
	    public virtual string componente_base { get; set; }
	    public virtual string producto_base { get; set; }
	    public virtual string fecha_inicio_real { get; set; }
	    public virtual string fecha_fin_real { get; set; }
	    public virtual string inversion_nueva { get; set; }
		public virtual acumulacion_costo acumulacion_costos { get; set; }
		public virtual actividad_tipo actividad_tipos { get; set; }
		public virtual IEnumerable<actividad> actividads { get; set; }
	}
}
