
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ASIGNACION_RACI table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("asignacion_raci")]
	public partial class asignacion_raci
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("matriz_raci")]
        public virtual string matriz_raciid { get; set; }
	    [ForeignKey("colaborador")]
        public virtual string colaboradorid { get; set; }
	    public virtual string rol_raci { get; set; }
	    public virtual string objeto_id { get; set; }
	    public virtual string objeto_tipo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual colaborador colaboradors { get; set; }
		public virtual matriz_raci matriz_racis { get; set; }
		public virtual IEnumerable<asignacion_raci> asignacionracis { get; set; }
	}
}
