
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ATIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("atipo_propiedad")]
	public partial class atipo_propiedad
	{
		[Key]
	    [ForeignKey("actividad_tipo")]
        public virtual string actividad_tipoid { get; set; }
		[Key]
	    [ForeignKey("actividad_propiedad")]
        public virtual string actividad_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual actividad_propiedad actividad_propiedads { get; set; }
		public virtual actividad_tipo actividad_tipos { get; set; }
		public virtual IEnumerable<atipo_propiedad> atipopropiedads { get; set; }
	}
}
