
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the COLABORADOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("colaborador")]
	public partial class colaborador
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string pnombre { get; set; }
	    public virtual string snombre { get; set; }
	    public virtual string papellido { get; set; }
	    public virtual string sapellido { get; set; }
	    public virtual string cui { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string ueunidad_ejecutora { get; set; }
	    [ForeignKey("usuario")]
        public virtual string usuariousuario { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string ejercicio { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string entidad { get; set; }
		public virtual usuario usuarios { get; set; }
		public virtual unidad_ejecutora unidad_ejecutoras { get; set; }
		public virtual IEnumerable<colaborador> colaboradors { get; set; }
	}
}
