
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the COLABORADOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("COLABORADOR")]
	public partial class Colaborador
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual string pnombre { get; set; }
	    public virtual string snombre { get; set; }
	    public virtual string papellido { get; set; }
	    public virtual string sapellido { get; set; }
	    public virtual Int64 cui { get; set; }
	    [Column("UEUNIDAD_EJECUTORA")]
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32 ueunidadEjecutora { get; set; }
	    [ForeignKey("Usuario")]
        public virtual string usuariousuario { get; set; }
	    public virtual Int32 estado { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32 ejercicio { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32? entidad { get; set; }
		public virtual Usuario usuarios { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual IEnumerable<Colaborador> colaboradors { get; set; }
	}
}
