
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the COMPONENTE_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("COMPONENTE_PROPIEDAD_VALOR")]
	public partial class ComponentePropiedadValor
	{
		[Key]
	    [ForeignKey("Componente")]
        public virtual string componenteid { get; set; }
		[Key]
	    [ForeignKey("ComponentePropiedad")]
        public virtual string componentePropiedadid { get; set; }
	    public virtual string valorString { get; set; }
	    public virtual string valorEntero { get; set; }
	    public virtual string valorDecimal { get; set; }
	    public virtual string valorTiempo { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual ComponentePropiedad componentePropiedads { get; set; }
		public virtual Componente componentes { get; set; }
		public virtual IEnumerable<ComponentePropiedadValor> componentepropiedadvalors { get; set; }
	}
}
