
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the COMPONENTE_USUARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("COMPONENTE_USUARIO")]
	public partial class ComponenteUsuario
	{
		[Key]
	    [ForeignKey("Componente")]
        public virtual string componenteid { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual Componente componentes { get; set; }
		public virtual IEnumerable<ComponenteUsuario> componenteusuarios { get; set; }
	}
}
