
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the COOPERANTE table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("cooperante")]
	public partial class cooperante
	{
		[Key]
	    public virtual string codigo { get; set; }
	    public virtual string siglas { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
	}
}
