
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the CTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("ctipo_propiedad")]
	public partial class ctipo_propiedad
	{
		[Key]
	    [ForeignKey("componente_tipo")]
        public virtual string componente_tipoid { get; set; }
		[Key]
	    [ForeignKey("componente_propiedad")]
        public virtual string componente_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual componente_propiedad componente_propiedads { get; set; }
		public virtual componente_tipo componente_tipos { get; set; }
		public virtual IEnumerable<ctipo_propiedad> ctipopropiedads { get; set; }
	}
}
