
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the DESEMBOLSO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("DESEMBOLSO")]
	public partial class Desembolso
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string fecha { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string monto { get; set; }
	    public virtual string tipoCambio { get; set; }
	    public virtual string montoMonedaOrigen { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    [ForeignKey("Proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("DesembolsoTipo")]
        public virtual string desembolsoTipoid { get; set; }
	    [ForeignKey("TipoMoneda")]
        public virtual string tipoMonedaid { get; set; }
		public virtual TipoMoneda tipoMonedas { get; set; }
		public virtual DesembolsoTipo desembolsoTipos { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual IEnumerable<Desembolso> desembolsoes { get; set; }
	}
}
