
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the DESEMBOLSO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("desembolso")]
	public partial class desembolso
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string fecha { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string monto { get; set; }
	    public virtual string tipo_cambio { get; set; }
	    public virtual string monto_moneda_origen { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("desembolso_tipo")]
        public virtual string desembolso_tipoid { get; set; }
	    [ForeignKey("tipo_moneda")]
        public virtual string tipo_monedaid { get; set; }
		public virtual tipo_moneda tipo_monedas { get; set; }
		public virtual desembolso_tipo desembolso_tipos { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<desembolso> desembolsoes { get; set; }
	}
}
