
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the DOCUMENTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("DOCUMENTO")]
	public partial class Documento
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string extension { get; set; }
	    [Column("ID_TIPO_OBJETO")]
	    public virtual Int64 idTipoObjeto { get; set; }
	    [Column("ID_OBJETO")]
	    public virtual Int64 idObjeto { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
	}
}
