
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ENTIDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("entidad")]
	public partial class entidad
	{
		[Key]
	    public virtual string _entidad { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string abreviatura { get; set; }
	    public virtual string ejercicio { get; set; }
	}
}
