
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_OPCION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO_ITEM_OPCION")]
	public partial class FormularioItemOpcion
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    [Column("FORMULARIO_ITEMID")]
	    [ForeignKey("FormularioItem")]
        public virtual Int32 formularioItemid { get; set; }
	    public virtual string etiqueta { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual Int32? valorEntero { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual byte[] valorTiempo { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual decimal? valorDecimal { get; set; }
	    public virtual Int32 estado { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZACION")]
	    public virtual Int64? usuarioActualizacion { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual byte[] fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual byte[] fechaActualizacion { get; set; }
		public virtual FormularioItem formularioItems { get; set; }
		public virtual IEnumerable<FormularioItemOpcion> formularioitemopcions { get; set; }
	}
}
