
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("formulario")]
	public partial class formulario
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string codigo { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("formulario_tipo")]
        public virtual string formulario_tipoid { get; set; }
		public virtual formulario_tipo formulario_tipos { get; set; }
		public virtual IEnumerable<formulario> formularios { get; set; }
	}
}
