
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO")]
	public partial class Formulario
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string codigo { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("FormularioTipo")]
        public virtual string formularioTipoid { get; set; }
		public virtual FormularioTipo formularioTipos { get; set; }
		public virtual IEnumerable<Formulario> formularios { get; set; }
	}
}
