
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_OPCION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("formulario_item_opcion")]
	public partial class formulario_item_opcion
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("formulario_item")]
        public virtual string formulario_itemid { get; set; }
	    public virtual string etiqueta { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizacion { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual formulario_item formulario_items { get; set; }
		public virtual IEnumerable<formulario_item_opcion> formularioitemopcions { get; set; }
	}
}
