
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("formulario_item")]
	public partial class formulario_item
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string texto { get; set; }
	    [ForeignKey("formulario")]
        public virtual string formularioid { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizacion { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("formulario_item_tipo")]
        public virtual string formulario_item_tipoid { get; set; }
		public virtual formulario formularios { get; set; }
		public virtual formulario_item_tipo formulario_item_tipos { get; set; }
		public virtual IEnumerable<formulario_item> formularioitems { get; set; }
	}
}
