
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO_ITEM_VALOR")]
	public partial class FormularioItemValor
	{
		[Key]
	    [ForeignKey("FormularioItem")]
        public virtual string formularioItemid { get; set; }
		[Key]
	    [ForeignKey("ObjetoFormulario")]
        public virtual string objetoFormularioformularioid { get; set; }
		[Key]
	    [ForeignKey("ObjetoFormulario")]
        public virtual string objetoFormularioobjetoTipoid { get; set; }
	    public virtual string valorEntero { get; set; }
	    public virtual string valorString { get; set; }
	    public virtual string valorTiempo { get; set; }
	    public virtual string valorDecimal { get; set; }
	    public virtual string proyectoid { get; set; }
	    public virtual string componenteid { get; set; }
	    public virtual string productoid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		[Key]
	    [ForeignKey("ObjetoFormulario")]
        public virtual string objetoFormularioobjetoId { get; set; }
		public virtual ObjetoFormulario objetoFormularios { get; set; }
		public virtual FormularioItem formularioItems { get; set; }
		public virtual IEnumerable<FormularioItemValor> formularioitemvalors { get; set; }
	}
}
