
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("formulario_item_valor")]
	public partial class formulario_item_valor
	{
		[Key]
	    [ForeignKey("formulario_item")]
        public virtual string formulario_itemid { get; set; }
		[Key]
	    [ForeignKey("objeto_formulario")]
        public virtual string objeto_formularioformularioid { get; set; }
		[Key]
	    [ForeignKey("objeto_formulario")]
        public virtual string objeto_formularioobjeto_tipoid { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string proyectoid { get; set; }
	    public virtual string componenteid { get; set; }
	    public virtual string productoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		[Key]
	    [ForeignKey("objeto_formulario")]
        public virtual string objeto_formularioobjeto_id { get; set; }
		public virtual objeto_formulario objeto_formularios { get; set; }
		public virtual formulario_item formulario_items { get; set; }
		public virtual IEnumerable<formulario_item_valor> formularioitemvalors { get; set; }
	}
}
