
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_OPCION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO_ITEM_OPCION")]
	public partial class FormularioItemOpcion
	{
		[Key]
	    public virtual string id { get; set; }
	    [Column("FORMULARIO_ITEMID")]
	    [ForeignKey("FormularioItem")]
        public virtual string formularioItemid { get; set; }
	    public virtual string etiqueta { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual string valorEntero { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual string valorTiempo { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual string valorDecimal { get; set; }
	    public virtual string estado { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZACION")]
	    public virtual string usuarioActualizacion { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
		public virtual FormularioItem formularioItems { get; set; }
		public virtual IEnumerable<FormularioItemOpcion> formularioitemopcions { get; set; }
	}
}
