
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the FORMULARIO_ITEM_TIPO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("FORMULARIO_ITEM_TIPO")]
	public partial class FormularioItemTipo
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string usuarioActualizacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    [ForeignKey("DatoTipo")]
        public virtual string datoTipoid { get; set; }
		public virtual DatoTipo datoTipos { get; set; }
		public virtual IEnumerable<FormularioItemTipo> formularioitemtipoes { get; set; }
	}
}
