
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the HITO_RESULTADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("hito_resultado")]
	public partial class hito_resultado
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string comentario { get; set; }
	    [ForeignKey("hito")]
        public virtual string hitoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual hito hitos { get; set; }
		public virtual IEnumerable<hito_resultado> hitoresultadoes { get; set; }
	}
}
