
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the HITO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("hito")]
	public partial class hito
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string fecha { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("hito_tipo")]
        public virtual string hito_tipoid { get; set; }
		public virtual hito_tipo hito_tipos { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<hito> hitoes { get; set; }
	}
}
