
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the LINEA_BASE table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("linea_base")]
	public partial class linea_base
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string tipo_linea_base { get; set; }
	    public virtual string sobreescribir { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<linea_base> lineabases { get; set; }
	}
}
