
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MATRIZ_RACI table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("matriz_raci")]
	public partial class matriz_raci
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<matriz_raci> matrizracis { get; set; }
	}
}
