
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MATRIZ_RACI table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MATRIZ_RACI")]
	public partial class MatrizRaci
	{
		[Key]
	    public virtual Int64 id { get; set; }
	    [ForeignKey("Proyecto")]
        public virtual Int32 proyectoid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual byte[] fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual byte[] fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual IEnumerable<MatrizRaci> matrizracis { get; set; }
	}
}
