
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MATRIZ_RACI table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MATRIZ_RACI")]
	public partial class MatrizRaci
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("Proyecto")]
        public virtual string proyectoid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual IEnumerable<MatrizRaci> matrizracis { get; set; }
	}
}
