
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("meta_valor")]
	public partial class meta_valor
	{
		[Key]
	    [ForeignKey("meta")]
        public virtual string metaid { get; set; }
		[Key]
	    public virtual string fecha { get; set; }
	    public virtual string usuario { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
		public virtual meta metas { get; set; }
		public virtual IEnumerable<meta_valor> metavalors { get; set; }
	}
}
