
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META_PLANIFICADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("META_PLANIFICADO")]
	public partial class MetaPlanificado
	{
		[Key]
	    [ForeignKey("Meta")]
        public virtual string metaid { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
	    [Column("ENERO_ENTERO")]
	    public virtual string eneroEntero { get; set; }
	    [Column("ENERO_STRING")]
	    public virtual string eneroString { get; set; }
	    [Column("ENERO_DECIMAL")]
	    public virtual string eneroDecimal { get; set; }
	    [Column("ENERO_TIEMPO")]
	    public virtual string eneroTiempo { get; set; }
	    [Column("FEBRERO_ENTERO")]
	    public virtual string febreroEntero { get; set; }
	    [Column("FEBRERO_STRING")]
	    public virtual string febreroString { get; set; }
	    [Column("FEBRERO_DECIMAL")]
	    public virtual string febreroDecimal { get; set; }
	    [Column("FEBRERO_TIEMPO")]
	    public virtual string febreroTiempo { get; set; }
	    [Column("MARZO_ENTERO")]
	    public virtual string marzoEntero { get; set; }
	    [Column("MARZO_STRING")]
	    public virtual string marzoString { get; set; }
	    [Column("MARZO_DECIMAL")]
	    public virtual string marzoDecimal { get; set; }
	    [Column("MARZO_TIEMPO")]
	    public virtual string marzoTiempo { get; set; }
	    [Column("ABRIL_ENTERO")]
	    public virtual string abrilEntero { get; set; }
	    [Column("ABRIL_STRING")]
	    public virtual string abrilString { get; set; }
	    [Column("ABRIL_DECIMAL")]
	    public virtual string abrilDecimal { get; set; }
	    [Column("ABRIL_TIEMPO")]
	    public virtual string abrilTiempo { get; set; }
	    [Column("MAYO_ENTERO")]
	    public virtual string mayoEntero { get; set; }
	    [Column("MAYO_STRING")]
	    public virtual string mayoString { get; set; }
	    [Column("MAYO_DECIMAL")]
	    public virtual string mayoDecimal { get; set; }
	    [Column("MAYO_TIEMPO")]
	    public virtual string mayoTiempo { get; set; }
	    [Column("JUNIO_ENTERO")]
	    public virtual string junioEntero { get; set; }
	    [Column("JUNIO_STRING")]
	    public virtual string junioString { get; set; }
	    [Column("JUNIO_DECIMAL")]
	    public virtual string junioDecimal { get; set; }
	    [Column("JUNIO_TIEMPO")]
	    public virtual string junioTiempo { get; set; }
	    [Column("JULIO_ENTERO")]
	    public virtual string julioEntero { get; set; }
	    [Column("JULIO_STRING")]
	    public virtual string julioString { get; set; }
	    [Column("JULIO_DECIMAL")]
	    public virtual string julioDecimal { get; set; }
	    [Column("JULIO_TIEMPO")]
	    public virtual string julioTiempo { get; set; }
	    [Column("AGOSTO_ENTERO")]
	    public virtual string agostoEntero { get; set; }
	    [Column("AGOSTO_STRING")]
	    public virtual string agostoString { get; set; }
	    [Column("AGOSTO_DECIMAL")]
	    public virtual string agostoDecimal { get; set; }
	    [Column("AGOSTO_TIEMPO")]
	    public virtual string agostoTiempo { get; set; }
	    [Column("SEPTIEMBRE_ENTERO")]
	    public virtual string septiembreEntero { get; set; }
	    [Column("SEPTIEMBRE_STRING")]
	    public virtual string septiembreString { get; set; }
	    [Column("SEPTIEMBRE_DECIMAL")]
	    public virtual string septiembreDecimal { get; set; }
	    [Column("SEPTIEMBRE_TIEMPO")]
	    public virtual string septiembreTiempo { get; set; }
	    [Column("OCTUBRE_ENTERO")]
	    public virtual string octubreEntero { get; set; }
	    [Column("OCTUBRE_STRING")]
	    public virtual string octubreString { get; set; }
	    [Column("OCTUBRE_DECIMAL")]
	    public virtual string octubreDecimal { get; set; }
	    [Column("OCTUBRE_TIEMPO")]
	    public virtual string octubreTiempo { get; set; }
	    [Column("NOVIEMBRE_ENTERO")]
	    public virtual string noviembreEntero { get; set; }
	    [Column("NOVIEMBRE_STRING")]
	    public virtual string noviembreString { get; set; }
	    [Column("NOVIEMBRE_DECIMAL")]
	    public virtual string noviembreDecimal { get; set; }
	    [Column("NOVIEMBRE_TIEMPO")]
	    public virtual string noviembreTiempo { get; set; }
	    [Column("DICIEMBRE_ENTERO")]
	    public virtual string diciembreEntero { get; set; }
	    [Column("DICIEMBRE_STRING")]
	    public virtual string diciembreString { get; set; }
	    [Column("DICIEMBRE_DECIMAL")]
	    public virtual string diciembreDecimal { get; set; }
	    [Column("DICIEMBRE_TIEMPO")]
	    public virtual string diciembreTiempo { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario { get; set; }
	    [Column("FECHA_INGRESO")]
	    public virtual string fechaIngreso { get; set; }
		public virtual Meta metas { get; set; }
		public virtual IEnumerable<MetaPlanificado> metaplanificadoes { get; set; }
	}
}
