
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("META")]
	public partial class Meta
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [Column("META_UNIDAD_MEDIDAID")]
	    [ForeignKey("MetaUnidadMedida")]
        public virtual string metaUnidadMedidaid { get; set; }
	    [Column("DATO_TIPOID")]
	    [ForeignKey("DatoTipo")]
        public virtual string datoTipoid { get; set; }
	    [Column("OBJETO_ID")]
	    public virtual string objetoId { get; set; }
	    [Column("OBJETO_TIPO")]
	    public virtual string objetoTipo { get; set; }
	    [Column("META_FINAL_ENTERO")]
	    public virtual string metaFinalEntero { get; set; }
	    [Column("META_FINAL_STRING")]
	    public virtual string metaFinalString { get; set; }
	    [Column("META_FINAL_DECIMAL")]
	    public virtual string metaFinalDecimal { get; set; }
	    [Column("META_FINAL_FECHA")]
	    public virtual string metaFinalFecha { get; set; }
		public virtual DatoTipo datoTipos { get; set; }
		public virtual MetaUnidadMedida metaUnidadMedidas { get; set; }
		public virtual IEnumerable<Meta> metas { get; set; }
	}
}
