
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("meta")]
	public partial class meta
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("meta_unidad_medida")]
        public virtual string meta_unidad_medidaid { get; set; }
	    [ForeignKey("dato_tipo")]
        public virtual string dato_tipoid { get; set; }
	    public virtual string objeto_id { get; set; }
	    public virtual string objeto_tipo { get; set; }
	    public virtual string meta_final_entero { get; set; }
	    public virtual string meta_final_string { get; set; }
	    public virtual string meta_final_decimal { get; set; }
	    public virtual string meta_final_fecha { get; set; }
		public virtual dato_tipo dato_tipos { get; set; }
		public virtual meta_unidad_medida meta_unidad_medidas { get; set; }
		public virtual IEnumerable<meta> metas { get; set; }
	}
}
