
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META_PLANIFICADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("meta_planificado")]
	public partial class meta_planificado
	{
		[Key]
	    [ForeignKey("meta")]
        public virtual string metaid { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
	    public virtual string enero_entero { get; set; }
	    public virtual string enero_string { get; set; }
	    public virtual string enero_decimal { get; set; }
	    public virtual string enero_tiempo { get; set; }
	    public virtual string febrero_entero { get; set; }
	    public virtual string febrero_string { get; set; }
	    public virtual string febrero_decimal { get; set; }
	    public virtual string febrero_tiempo { get; set; }
	    public virtual string marzo_entero { get; set; }
	    public virtual string marzo_string { get; set; }
	    public virtual string marzo_decimal { get; set; }
	    public virtual string marzo_tiempo { get; set; }
	    public virtual string abril_entero { get; set; }
	    public virtual string abril_string { get; set; }
	    public virtual string abril_decimal { get; set; }
	    public virtual string abril_tiempo { get; set; }
	    public virtual string mayo_entero { get; set; }
	    public virtual string mayo_string { get; set; }
	    public virtual string mayo_decimal { get; set; }
	    public virtual string mayo_tiempo { get; set; }
	    public virtual string junio_entero { get; set; }
	    public virtual string junio_string { get; set; }
	    public virtual string junio_decimal { get; set; }
	    public virtual string junio_tiempo { get; set; }
	    public virtual string julio_entero { get; set; }
	    public virtual string julio_string { get; set; }
	    public virtual string julio_decimal { get; set; }
	    public virtual string julio_tiempo { get; set; }
	    public virtual string agosto_entero { get; set; }
	    public virtual string agosto_string { get; set; }
	    public virtual string agosto_decimal { get; set; }
	    public virtual string agosto_tiempo { get; set; }
	    public virtual string septiembre_entero { get; set; }
	    public virtual string septiembre_string { get; set; }
	    public virtual string septiembre_decimal { get; set; }
	    public virtual string septiembre_tiempo { get; set; }
	    public virtual string octubre_entero { get; set; }
	    public virtual string octubre_string { get; set; }
	    public virtual string octubre_decimal { get; set; }
	    public virtual string octubre_tiempo { get; set; }
	    public virtual string noviembre_entero { get; set; }
	    public virtual string noviembre_string { get; set; }
	    public virtual string noviembre_decimal { get; set; }
	    public virtual string noviembre_tiempo { get; set; }
	    public virtual string diciembre_entero { get; set; }
	    public virtual string diciembre_string { get; set; }
	    public virtual string diciembre_decimal { get; set; }
	    public virtual string diciembre_tiempo { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario { get; set; }
	    public virtual string fecha_ingreso { get; set; }
		public virtual meta metas { get; set; }
		public virtual IEnumerable<meta_planificado> metaplanificadoes { get; set; }
	}
}
