
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META_PLANIFICADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("META_PLANIFICADO")]
	public partial class MetaPlanificado
	{
		[Key]
	    [ForeignKey("Meta")]
        public virtual string metaid { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
	    public virtual string eneroEntero { get; set; }
	    public virtual string eneroString { get; set; }
	    public virtual string eneroDecimal { get; set; }
	    public virtual string eneroTiempo { get; set; }
	    public virtual string febreroEntero { get; set; }
	    public virtual string febreroString { get; set; }
	    public virtual string febreroDecimal { get; set; }
	    public virtual string febreroTiempo { get; set; }
	    public virtual string marzoEntero { get; set; }
	    public virtual string marzoString { get; set; }
	    public virtual string marzoDecimal { get; set; }
	    public virtual string marzoTiempo { get; set; }
	    public virtual string abrilEntero { get; set; }
	    public virtual string abrilString { get; set; }
	    public virtual string abrilDecimal { get; set; }
	    public virtual string abrilTiempo { get; set; }
	    public virtual string mayoEntero { get; set; }
	    public virtual string mayoString { get; set; }
	    public virtual string mayoDecimal { get; set; }
	    public virtual string mayoTiempo { get; set; }
	    public virtual string junioEntero { get; set; }
	    public virtual string junioString { get; set; }
	    public virtual string junioDecimal { get; set; }
	    public virtual string junioTiempo { get; set; }
	    public virtual string julioEntero { get; set; }
	    public virtual string julioString { get; set; }
	    public virtual string julioDecimal { get; set; }
	    public virtual string julioTiempo { get; set; }
	    public virtual string agostoEntero { get; set; }
	    public virtual string agostoString { get; set; }
	    public virtual string agostoDecimal { get; set; }
	    public virtual string agostoTiempo { get; set; }
	    public virtual string septiembreEntero { get; set; }
	    public virtual string septiembreString { get; set; }
	    public virtual string septiembreDecimal { get; set; }
	    public virtual string septiembreTiempo { get; set; }
	    public virtual string octubreEntero { get; set; }
	    public virtual string octubreString { get; set; }
	    public virtual string octubreDecimal { get; set; }
	    public virtual string octubreTiempo { get; set; }
	    public virtual string noviembreEntero { get; set; }
	    public virtual string noviembreString { get; set; }
	    public virtual string noviembreDecimal { get; set; }
	    public virtual string noviembreTiempo { get; set; }
	    public virtual string diciembreEntero { get; set; }
	    public virtual string diciembreString { get; set; }
	    public virtual string diciembreDecimal { get; set; }
	    public virtual string diciembreTiempo { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario { get; set; }
	    public virtual string fechaIngreso { get; set; }
		public virtual Meta metas { get; set; }
		public virtual IEnumerable<MetaPlanificado> metaplanificadoes { get; set; }
	}
}
