
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the META_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("META_VALOR")]
	public partial class MetaValor
	{
		[Key]
	    [ForeignKey("Meta")]
        public virtual string metaid { get; set; }
		[Key]
	    public virtual string fecha { get; set; }
	    public virtual string usuario { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual string valorEntero { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual string valorDecimal { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual string valorTiempo { get; set; }
		public virtual Meta metas { get; set; }
		public virtual IEnumerable<MetaValor> metavalors { get; set; }
	}
}
