
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PAGO_PLANIFICADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("pago_planificado")]
	public partial class pago_planificado
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string fecha_pago { get; set; }
	    public virtual string pago { get; set; }
	    public virtual string objeto_id { get; set; }
	    public virtual string objeto_tipo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	}
}
