
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PAGO_PLANIFICADO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PAGO_PLANIFICADO")]
	public partial class PagoPlanificado
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string fechaPago { get; set; }
	    public virtual string pago { get; set; }
	    public virtual string objetoId { get; set; }
	    public virtual string objetoTipo { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	}
}
