
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PEP_DETALLE table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("pep_detalle")]
	public partial class pep_detalle
	{
		[Key]
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    public virtual string observaciones { get; set; }
	    public virtual string alertivos { get; set; }
	    public virtual string elaborado { get; set; }
	    public virtual string aprobado { get; set; }
	    public virtual string autoridad { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<pep_detalle> pepdetalles { get; set; }
	}
}
