
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PLAN_ADQUISICION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("plan_adquisicion")]
	public partial class plan_adquisicion
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("tipo_adquisicion")]
        public virtual string tipo_adquisicion { get; set; }
	    [ForeignKey("categoria_adquisicion")]
        public virtual string categoria_adquisicion { get; set; }
	    public virtual string unidad_medida { get; set; }
	    public virtual string cantidad { get; set; }
	    public virtual string total { get; set; }
	    public virtual string precio_unitario { get; set; }
	    public virtual string preparacion_doc_planificado { get; set; }
	    public virtual string preparacion_doc_real { get; set; }
	    public virtual string lanzamiento_evento_planificado { get; set; }
	    public virtual string lanzamiento_evento_real { get; set; }
	    public virtual string recepcion_ofertas_planificado { get; set; }
	    public virtual string recepcion_ofertas_real { get; set; }
	    public virtual string adjudicacion_planificado { get; set; }
	    public virtual string adjudicacion_real { get; set; }
	    public virtual string firma_contrato_planificado { get; set; }
	    public virtual string firma_contrato_real { get; set; }
	    public virtual string objeto_id { get; set; }
	    public virtual string objeto_tipo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string bloqueado { get; set; }
	    public virtual string numero_contrato { get; set; }
	    public virtual string monto_contrato { get; set; }
	    public virtual string nog { get; set; }
	    public virtual string tipo_revision { get; set; }
		public virtual categoria_adquisicion categoria_adquisicions { get; set; }
		public virtual tipo_adquisicion tipo_adquisicions { get; set; }
		public virtual IEnumerable<plan_adquisicion> planadquisicions { get; set; }
	}
}
