
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PLAN_ADQUISICION_PAGO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PLAN_ADQUISICION_PAGO")]
	public partial class PlanAdquisicionPago
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("PlanAdquisicion")]
        public virtual string planAdquisicionid { get; set; }
	    public virtual string fechaPago { get; set; }
	    public virtual string pago { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual PlanAdquisicion planAdquisicions { get; set; }
		public virtual IEnumerable<PlanAdquisicionPago> planadquisicionpagoes { get; set; }
	}
}
