
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PLAN_ADQUISICION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PLAN_ADQUISICION")]
	public partial class PlanAdquisicion
	{
		[Key]
	    public virtual string id { get; set; }
	    [Column("TIPO_ADQUISICION")]
	    [ForeignKey("TipoAdquisicion")]
        public virtual string tipoAdquisicion { get; set; }
	    [Column("CATEGORIA_ADQUISICION")]
	    [ForeignKey("CategoriaAdquisicion")]
        public virtual string categoriaAdquisicion { get; set; }
	    [Column("UNIDAD_MEDIDA")]
	    public virtual string unidadMedida { get; set; }
	    public virtual string cantidad { get; set; }
	    public virtual string total { get; set; }
	    [Column("PRECIO_UNITARIO")]
	    public virtual string precioUnitario { get; set; }
	    [Column("PREPARACION_DOC_PLANIFICADO")]
	    public virtual string preparacionDocPlanificado { get; set; }
	    [Column("PREPARACION_DOC_REAL")]
	    public virtual string preparacionDocReal { get; set; }
	    [Column("LANZAMIENTO_EVENTO_PLANIFICADO")]
	    public virtual string lanzamientoEventoPlanificado { get; set; }
	    [Column("LANZAMIENTO_EVENTO_REAL")]
	    public virtual string lanzamientoEventoReal { get; set; }
	    [Column("RECEPCION_OFERTAS_PLANIFICADO")]
	    public virtual string recepcionOfertasPlanificado { get; set; }
	    [Column("RECEPCION_OFERTAS_REAL")]
	    public virtual string recepcionOfertasReal { get; set; }
	    [Column("ADJUDICACION_PLANIFICADO")]
	    public virtual string adjudicacionPlanificado { get; set; }
	    [Column("ADJUDICACION_REAL")]
	    public virtual string adjudicacionReal { get; set; }
	    [Column("FIRMA_CONTRATO_PLANIFICADO")]
	    public virtual string firmaContratoPlanificado { get; set; }
	    [Column("FIRMA_CONTRATO_REAL")]
	    public virtual string firmaContratoReal { get; set; }
	    [Column("OBJETO_ID")]
	    public virtual string objetoId { get; set; }
	    [Column("OBJETO_TIPO")]
	    public virtual string objetoTipo { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string bloqueado { get; set; }
	    [Column("NUMERO_CONTRATO")]
	    public virtual string numeroContrato { get; set; }
	    [Column("MONTO_CONTRATO")]
	    public virtual string montoContrato { get; set; }
	    public virtual string nog { get; set; }
	    [Column("TIPO_REVISION")]
	    public virtual string tipoRevision { get; set; }
		public virtual CategoriaAdquisicion categoriaAdquisicions { get; set; }
		public virtual TipoAdquisicion tipoAdquisicions { get; set; }
		public virtual IEnumerable<PlanAdquisicion> planadquisicions { get; set; }
	}
}
