
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PLAN_ADQUISICION_PAGO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("plan_adquisicion_pago")]
	public partial class plan_adquisicion_pago
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("plan_adquisicion")]
        public virtual string plan_adquisicionid { get; set; }
	    public virtual string fecha_pago { get; set; }
	    public virtual string pago { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual plan_adquisicion plan_adquisicions { get; set; }
		public virtual IEnumerable<plan_adquisicion_pago> planadquisicionpagoes { get; set; }
	}
}
