
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRESTAMO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRESTAMO")]
	public partial class Prestamo
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string fechaCorte { get; set; }
	    public virtual string codigoPresupuestario { get; set; }
	    public virtual string numeroPrestamo { get; set; }
	    public virtual string destino { get; set; }
	    public virtual string sectorEconomico { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ueunidadEjecutora { get; set; }
	    public virtual string fechaFirma { get; set; }
	    public virtual string autorizacionTipoid { get; set; }
	    public virtual string numeroAutorizacion { get; set; }
	    public virtual string fechaAutorizacion { get; set; }
	    public virtual string aniosPlazo { get; set; }
	    public virtual string aniosGracia { get; set; }
	    public virtual string fechaFinEjecucion { get; set; }
	    public virtual string peridoEjecucion { get; set; }
	    public virtual string interesTipoid { get; set; }
	    public virtual string porcentajeInteres { get; set; }
	    public virtual string porcentajeComisionCompra { get; set; }
	    [ForeignKey("TipoMoneda")]
        public virtual string tipoMonedaid { get; set; }
	    public virtual string montoContratado { get; set; }
	    public virtual string amortizado { get; set; }
	    public virtual string porAmortizar { get; set; }
	    public virtual string principalAnio { get; set; }
	    public virtual string interesesAnio { get; set; }
	    public virtual string comisionCompromisoAnio { get; set; }
	    public virtual string otrosGastos { get; set; }
	    public virtual string principalAcumulado { get; set; }
	    public virtual string interesesAcumulados { get; set; }
	    public virtual string comisionCompromisoAcumulado { get; set; }
	    public virtual string otrosCargosAcumulados { get; set; }
	    public virtual string presupuestoAsignadoFunc { get; set; }
	    public virtual string prespupuestoAsignadoInv { get; set; }
	    public virtual string presupuestoModificadoFunc { get; set; }
	    public virtual string presupuestoModificadoInv { get; set; }
	    public virtual string presupuestoVigenteFunc { get; set; }
	    public virtual string presupuestoVigenteInv { get; set; }
	    public virtual string prespupuestoDevengadoFunc { get; set; }
	    public virtual string presupuestoDevengadoInv { get; set; }
	    public virtual string presupuestoPagadoFunc { get; set; }
	    public virtual string presupuestoPagadoInv { get; set; }
	    public virtual string saldoCuentas { get; set; }
	    public virtual string desembolsadoReal { get; set; }
	    public virtual string ejecucionEstadoid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string proyectoPrograma { get; set; }
	    public virtual string fechaDecreto { get; set; }
	    public virtual string fechaSuscripcion { get; set; }
	    public virtual string fechaElegibilidadUe { get; set; }
	    public virtual string fechaCierreOrigianlUe { get; set; }
	    public virtual string fechaCierreActualUe { get; set; }
	    public virtual string mesesProrrogaUe { get; set; }
	    public virtual string plazoEjecucionUe { get; set; }
	    public virtual string montoAsignadoUe { get; set; }
	    public virtual string desembolsoAFechaUe { get; set; }
	    public virtual string montoPorDesembolsarUe { get; set; }
	    public virtual string fechaVigencia { get; set; }
	    public virtual string montoContratadoUsd { get; set; }
	    public virtual string montoContratadoQtz { get; set; }
	    public virtual string desembolsoAFechaUsd { get; set; }
	    public virtual string montoPorDesembolsarUsd { get; set; }
	    public virtual string montoAsignadoUeUsd { get; set; }
	    public virtual string montoAsignadoUeQtz { get; set; }
	    public virtual string desembolsoAFechaUeUsd { get; set; }
	    public virtual string montoPorDesembolsarUeUsd { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string entidad { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ejercicio { get; set; }
	    public virtual string objetivo { get; set; }
	    public virtual string objetivoEspecifico { get; set; }
	    [ForeignKey("Cooperante")]
        public virtual string cooperantecodigo { get; set; }
	    [ForeignKey("Cooperante")]
        public virtual string cooperanteejercicio { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual Cooperante cooperantes { get; set; }
		public virtual TipoMoneda tipoMonedas { get; set; }
		public virtual IEnumerable<Prestamo> prestamoes { get; set; }
	}
}
