
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRESTAMO_TIPO_PRESTAMO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("prestamo_tipo_prestamo")]
	public partial class prestamo_tipo_prestamo
	{
	    [ForeignKey("prestamo")]
        public virtual string prestamoid { get; set; }
	    [ForeignKey("prestamo_tipo")]
        public virtual string tipoprestamoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual prestamo_tipo prestamo_tipos { get; set; }
		public virtual prestamo prestamos { get; set; }
		public virtual IEnumerable<prestamo_tipo_prestamo> prestamotipoprestamoes { get; set; }
	}
}
