
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODUCTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRODUCTO_PROPIEDAD_VALOR")]
	public partial class ProductoPropiedadValor
	{
		[Key]
	    [ForeignKey("ProductoPropiedad")]
        public virtual string productoPropiedadid { get; set; }
		[Key]
	    [ForeignKey("Producto")]
        public virtual string productoid { get; set; }
	    public virtual string valorEntero { get; set; }
	    public virtual string valorString { get; set; }
	    public virtual string valorDecimal { get; set; }
	    public virtual string valorTiempo { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual Producto productos { get; set; }
		public virtual ProductoPropiedad productoPropiedads { get; set; }
		public virtual IEnumerable<ProductoPropiedadValor> productopropiedadvalors { get; set; }
	}
}
