
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("prodtipo_propiedad")]
	public partial class prodtipo_propiedad
	{
		[Key]
	    [ForeignKey("producto_tipo")]
        public virtual string producto_tipoid { get; set; }
		[Key]
	    [ForeignKey("producto_propiedad")]
        public virtual string producto_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual producto_propiedad producto_propiedads { get; set; }
		public virtual producto_tipo producto_tipos { get; set; }
		public virtual IEnumerable<prodtipo_propiedad> prodtipopropiedads { get; set; }
	}
}
