
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRODTIPO_PROPIEDAD")]
	public partial class ProdtipoPropiedad
	{
		[Key]
	    [Column("PRODUCTO_TIPOID")]
	    [ForeignKey("ProductoTipo")]
        public virtual string productoTipoid { get; set; }
		[Key]
	    [Column("PRODUCTO_PROPIEDADID")]
	    [ForeignKey("ProductoPropiedad")]
        public virtual string productoPropiedadid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
		public virtual ProductoPropiedad productoPropiedads { get; set; }
		public virtual ProductoTipo productoTipos { get; set; }
		public virtual IEnumerable<ProdtipoPropiedad> prodtipopropiedads { get; set; }
	}
}
