
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODUCTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("producto_propiedad_valor")]
	public partial class producto_propiedad_valor
	{
		[Key]
	    [ForeignKey("producto_propiedad")]
        public virtual string producto_propiedadid { get; set; }
		[Key]
	    [ForeignKey("producto")]
        public virtual string productoid { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual producto productos { get; set; }
		public virtual producto_propiedad producto_propiedads { get; set; }
		public virtual IEnumerable<producto_propiedad_valor> productopropiedadvalors { get; set; }
	}
}
