
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODUCTO_USUARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRODUCTO_USUARIO")]
	public partial class ProductoUsuario
	{
		[Key]
	    [ForeignKey("Producto")]
        public virtual string productoid { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual Producto productos { get; set; }
		public virtual IEnumerable<ProductoUsuario> productousuarios { get; set; }
	}
}
