
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PRODUCTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PRODUCTO")]
	public partial class Producto
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [ForeignKey("Componente")]
        public virtual string componenteid { get; set; }
	    [ForeignKey("Subcomponente")]
        public virtual string subcomponenteid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    [ForeignKey("ProductoTipo")]
        public virtual string productoTipoid { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ueunidadEjecutora { get; set; }
	    public virtual string snip { get; set; }
	    public virtual string programa { get; set; }
	    public virtual string subprograma { get; set; }
	    public virtual string proyecto { get; set; }
	    public virtual string actividad { get; set; }
	    public virtual string obra { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string peso { get; set; }
	    public virtual string costo { get; set; }
	    [ForeignKey("AcumulacionCosto")]
        public virtual string acumulacionCostoid { get; set; }
	    public virtual string renglon { get; set; }
	    public virtual string ubicacionGeografica { get; set; }
	    public virtual string fechaInicio { get; set; }
	    public virtual string fechaFin { get; set; }
	    public virtual string duracion { get; set; }
	    public virtual string duracionDimension { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual string nivel { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ejercicio { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string entidad { get; set; }
	    public virtual string fechaInicioReal { get; set; }
	    public virtual string fechaFinReal { get; set; }
	    public virtual string inversionNueva { get; set; }
	    public virtual string column { get; set; }
		public virtual AcumulacionCosto acumulacionCostos { get; set; }
		public virtual Subcomponente subcomponentes { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual ProductoTipo productoTipos { get; set; }
		public virtual Componente componentes { get; set; }
		public virtual IEnumerable<Producto> productoes { get; set; }
	}
}
