
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO")]
	public partial class Proyecto
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [ForeignKey("ProyectoTipo")]
        public virtual string proyectoTipoid { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ueunidadEjecutora { get; set; }
	    public virtual string snip { get; set; }
	    public virtual string programa { get; set; }
	    public virtual string subprograma { get; set; }
	    public virtual string proyecto { get; set; }
	    public virtual string actividad { get; set; }
	    public virtual string obra { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string objetivo { get; set; }
	    public virtual string directorProyecto { get; set; }
	    public virtual string enunciadoAlcance { get; set; }
	    public virtual string costo { get; set; }
	    [ForeignKey("AcumulacionCosto")]
        public virtual string acumulacionCostoid { get; set; }
	    public virtual string objetivoEspecifico { get; set; }
	    public virtual string visionGeneral { get; set; }
	    public virtual string renglon { get; set; }
	    public virtual string ubicacionGeografica { get; set; }
	    public virtual string fechaInicio { get; set; }
	    public virtual string fechaFin { get; set; }
	    public virtual string duracion { get; set; }
	    public virtual string duracionDimension { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual string nivel { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ejercicio { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string entidad { get; set; }
	    public virtual string ejecucionFisicaReal { get; set; }
	    public virtual string proyectoClase { get; set; }
	    public virtual string projectCargado { get; set; }
	    [ForeignKey("Prestamo")]
        public virtual string prestamoid { get; set; }
	    public virtual string observaciones { get; set; }
	    public virtual string coordinador { get; set; }
	    public virtual string fechaElegibilidad { get; set; }
	    public virtual string fechaCierre { get; set; }
	    public virtual string fechaInicioReal { get; set; }
	    public virtual string fechaFinReal { get; set; }
		public virtual Prestamo prestamos { get; set; }
		public virtual AcumulacionCosto acumulacionCostos { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual ProyectoTipo proyectoTipos { get; set; }
		public virtual IEnumerable<Proyecto> proyectoes { get; set; }
	}
}
