
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_MIEMBRO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("proyecto_miembro")]
	public partial class proyecto_miembro
	{
		[Key]
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
		[Key]
	    [ForeignKey("colaborador")]
        public virtual string colaboradorid { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
		public virtual colaborador colaboradors { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<proyecto_miembro> proyectomiembroes { get; set; }
	}
}
