
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO")]
	public partial class Proyecto
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual byte[] fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual byte[] fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
	    [Column("PROYECTO_TIPOID")]
	    [ForeignKey("ProyectoTipo")]
        public virtual Int32 proyectoTipoid { get; set; }
	    [Column("UEUNIDAD_EJECUTORA")]
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32 ueunidadEjecutora { get; set; }
	    public virtual Int32? snip { get; set; }
	    public virtual Int32? programa { get; set; }
	    public virtual Int32? subprograma { get; set; }
	    [Column("_PROYECTO")]
	    public virtual Int32? proyecto { get; set; }
	    public virtual Int32? actividad { get; set; }
	    public virtual Int32? obra { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string objetivo { get; set; }
	    [Column("DIRECTOR_PROYECTO")]
	    public virtual Int32? directorProyecto { get; set; }
	    [Column("ENUNCIADO_ALCANCE")]
	    public virtual string enunciadoAlcance { get; set; }
	    public virtual decimal? costo { get; set; }
	    [Column("ACUMULACION_COSTOID")]
	    [ForeignKey("AcumulacionCosto")]
        public virtual Int64 acumulacionCostoid { get; set; }
	    [Column("OBJETIVO_ESPECIFICO")]
	    public virtual string objetivoEspecifico { get; set; }
	    [Column("VISION_GENERAL")]
	    public virtual string visionGeneral { get; set; }
	    public virtual Int32? renglon { get; set; }
	    [Column("UBICACION_GEOGRAFICA")]
	    public virtual Int32? ubicacionGeografica { get; set; }
	    [Column("FECHA_INICIO")]
	    public virtual byte[] fechaInicio { get; set; }
	    [Column("FECHA_FIN")]
	    public virtual byte[] fechaFin { get; set; }
	    public virtual Int32 duracion { get; set; }
	    [Column("DURACION_DIMENSION")]
	    public virtual string duracionDimension { get; set; }
	    public virtual Int32? orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual Int32? nivel { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32 ejercicio { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual Int32? entidad { get; set; }
	    [Column("EJECUCION_FISICA_REAL")]
	    public virtual Int32? ejecucionFisicaReal { get; set; }
	    [Column("PROYECTO_CLASE")]
	    public virtual Int32 proyectoClase { get; set; }
	    [Column("PROJECT_CARGADO")]
	    public virtual Int32? projectCargado { get; set; }
	    [ForeignKey("Prestamo")]
        public virtual Int32? prestamoid { get; set; }
	    public virtual string observaciones { get; set; }
	    public virtual Int32? coordinador { get; set; }
	    [Column("FECHA_ELEGIBILIDAD")]
	    public virtual byte[] fechaElegibilidad { get; set; }
	    [Column("FECHA_INICIO_REAL")]
	    public virtual byte[] fechaInicioReal { get; set; }
	    [Column("FECHA_FIN_REAL")]
	    public virtual byte[] fechaFinReal { get; set; }
	    public virtual Int32? congelado { get; set; }
	    [Column("FECHA_CIERRE")]
	    public virtual byte[] fechaCierre { get; set; }
		public virtual Prestamo prestamos { get; set; }
		public virtual AcumulacionCosto acumulacionCostos { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual ProyectoTipo proyectoTipos { get; set; }
		public virtual IEnumerable<Proyecto> proyectoes { get; set; }
	}
}
