
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO")]
	public partial class Proyecto
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual string fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
	    [Column("PROYECTO_TIPOID")]
	    [ForeignKey("ProyectoTipo")]
        public virtual string proyectoTipoid { get; set; }
	    [Column("UEUNIDAD_EJECUTORA")]
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ueunidadEjecutora { get; set; }
	    public virtual string snip { get; set; }
	    public virtual string programa { get; set; }
	    public virtual string subprograma { get; set; }
	    [Column("_PROYECTO")]
	    public virtual string proyecto { get; set; }
	    public virtual string actividad { get; set; }
	    public virtual string obra { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string objetivo { get; set; }
	    [Column("DIRECTOR_PROYECTO")]
	    public virtual string directorProyecto { get; set; }
	    [Column("ENUNCIADO_ALCANCE")]
	    public virtual string enunciadoAlcance { get; set; }
	    public virtual string costo { get; set; }
	    [Column("ACUMULACION_COSTOID")]
	    [ForeignKey("AcumulacionCosto")]
        public virtual string acumulacionCostoid { get; set; }
	    [Column("OBJETIVO_ESPECIFICO")]
	    public virtual string objetivoEspecifico { get; set; }
	    [Column("VISION_GENERAL")]
	    public virtual string visionGeneral { get; set; }
	    public virtual string renglon { get; set; }
	    [Column("UBICACION_GEOGRAFICA")]
	    public virtual string ubicacionGeografica { get; set; }
	    [Column("FECHA_INICIO")]
	    public virtual string fechaInicio { get; set; }
	    [Column("FECHA_FIN")]
	    public virtual string fechaFin { get; set; }
	    public virtual string duracion { get; set; }
	    [Column("DURACION_DIMENSION")]
	    public virtual string duracionDimension { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual string nivel { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string ejercicio { get; set; }
	    [ForeignKey("UnidadEjecutora")]
        public virtual string entidad { get; set; }
	    [Column("EJECUCION_FISICA_REAL")]
	    public virtual string ejecucionFisicaReal { get; set; }
	    [Column("PROYECTO_CLASE")]
	    public virtual string proyectoClase { get; set; }
	    [Column("PROJECT_CARGADO")]
	    public virtual string projectCargado { get; set; }
	    [ForeignKey("Prestamo")]
        public virtual string prestamoid { get; set; }
	    public virtual string observaciones { get; set; }
	    public virtual string coordinador { get; set; }
	    [Column("FECHA_ELEGIBILIDAD")]
	    public virtual string fechaElegibilidad { get; set; }
	    [Column("FECHA_INICIO_REAL")]
	    public virtual string fechaInicioReal { get; set; }
	    [Column("FECHA_FIN_REAL")]
	    public virtual string fechaFinReal { get; set; }
	    public virtual string congelado { get; set; }
	    [Column("FECHA_CIERRE")]
	    public virtual string fechaCierre { get; set; }
		public virtual Prestamo prestamos { get; set; }
		public virtual AcumulacionCosto acumulacionCostos { get; set; }
		public virtual UnidadEjecutora unidadEjecutoras { get; set; }
		public virtual ProyectoTipo proyectoTipos { get; set; }
		public virtual IEnumerable<Proyecto> proyectoes { get; set; }
	}
}
