
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_ROL_COLABORADOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO_ROL_COLABORADOR")]
	public partial class ProyectoRolColaborador
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("Colaborador")]
        public virtual string colaboradorid { get; set; }
	    [ForeignKey("Proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("RolUnidadEjecutora")]
        public virtual string rolUnidadEjecutoraid { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual RolUnidadEjecutora rolUnidadEjecutoras { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual Colaborador colaboradors { get; set; }
		public virtual IEnumerable<ProyectoRolColaborador> proyectorolcolaboradors { get; set; }
	}
}
