
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_IMPACTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO_IMPACTO")]
	public partial class ProyectoImpacto
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("Proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("Entidad")]
        public virtual string entidadentidad { get; set; }
	    public virtual string impacto { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string ejercicio { get; set; }
		public virtual Entidad entidads { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual IEnumerable<ProyectoImpacto> proyectoimpactoes { get; set; }
	}
}
