
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_USUARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PROYECTO_USUARIO")]
	public partial class ProyectoUsuario
	{
		[Key]
	    [ForeignKey("Proyecto")]
        public virtual string proyectoid { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual Proyecto proyectos { get; set; }
		public virtual IEnumerable<ProyectoUsuario> proyectousuarios { get; set; }
	}
}
