
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("proyecto_propiedad_valor")]
	public partial class proyecto_propiedad_valor
	{
		[Key]
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
		[Key]
	    [ForeignKey("proyecto_propiedad")]
        public virtual string proyecto_propiedadid { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual proyecto_propiedad proyecto_propiedads { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<proyecto_propiedad_valor> proyectopropiedadvalors { get; set; }
	}
}
