
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_IMPACTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("proyecto_impacto")]
	public partial class proyecto_impacto
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("entidad")]
        public virtual string entidadentidad { get; set; }
	    public virtual string impacto { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string ejercicio { get; set; }
		public virtual entidad entidads { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual IEnumerable<proyecto_impacto> proyectoimpactoes { get; set; }
	}
}
