
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PROYECTO_ROL_COLABORADOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("proyecto_rol_colaborador")]
	public partial class proyecto_rol_colaborador
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("colaborador")]
        public virtual string colaboradorid { get; set; }
	    [ForeignKey("proyecto")]
        public virtual string proyectoid { get; set; }
	    [ForeignKey("rol_unidad_ejecutora")]
        public virtual string rol_unidad_ejecutoraid { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual rol_unidad_ejecutora rol_unidad_ejecutoras { get; set; }
		public virtual proyecto proyectos { get; set; }
		public virtual colaborador colaboradors { get; set; }
		public virtual IEnumerable<proyecto_rol_colaborador> proyectorolcolaboradors { get; set; }
	}
}
