
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("PTIPO_PROPIEDAD")]
	public partial class PtipoPropiedad
	{
		[Key]
	    [ForeignKey("ProyectoTipo")]
        public virtual string proyectoTipoid { get; set; }
		[Key]
	    [ForeignKey("ProyectoPropiedad")]
        public virtual string proyectoPropiedadid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual ProyectoPropiedad proyectoPropiedads { get; set; }
		public virtual ProyectoTipo proyectoTipos { get; set; }
		public virtual IEnumerable<PtipoPropiedad> ptipopropiedads { get; set; }
	}
}
