
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the PTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("ptipo_propiedad")]
	public partial class ptipo_propiedad
	{
		[Key]
	    [ForeignKey("proyecto_tipo")]
        public virtual string proyecto_tipoid { get; set; }
		[Key]
	    [ForeignKey("proyecto_propiedad")]
        public virtual string proyecto_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual proyecto_propiedad proyecto_propiedads { get; set; }
		public virtual proyecto_tipo proyecto_tipos { get; set; }
		public virtual IEnumerable<ptipo_propiedad> ptipopropiedads { get; set; }
	}
}
