
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the RIESGO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("riesgo")]
	public partial class riesgo
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [ForeignKey("riesgo_tipo")]
        public virtual string riesgo_tipoid { get; set; }
	    public virtual string impacto { get; set; }
	    public virtual string probabilidad { get; set; }
	    public virtual string impacto_monto { get; set; }
	    public virtual string impacto_tiempo { get; set; }
	    public virtual string gatillo { get; set; }
	    public virtual string consecuencia { get; set; }
	    public virtual string solucion { get; set; }
	    public virtual string riesgos_segundarios { get; set; }
	    public virtual string ejecutado { get; set; }
	    public virtual string fecha_ejecucion { get; set; }
	    public virtual string resultado { get; set; }
	    public virtual string observaciones { get; set; }
	    [ForeignKey("colaborador")]
        public virtual string colaboradorid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual colaborador colaboradors { get; set; }
		public virtual riesgo_tipo riesgo_tipos { get; set; }
		public virtual IEnumerable<riesgo> riesgoes { get; set; }
	}
}
