
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the RIESGO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("RIESGO_PROPIEDAD_VALOR")]
	public partial class RiesgoPropiedadValor
	{
		[Key]
	    [ForeignKey("Riesgo")]
        public virtual string riesgoid { get; set; }
		[Key]
	    [ForeignKey("RiesgoPropiedad")]
        public virtual string riesgoPropiedadid { get; set; }
	    public virtual string valorEntero { get; set; }
	    public virtual string valorString { get; set; }
	    public virtual string valorDecimal { get; set; }
	    public virtual string valorTiempo { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual RiesgoPropiedad riesgoPropiedads { get; set; }
		public virtual Riesgo riesgos { get; set; }
		public virtual IEnumerable<RiesgoPropiedadValor> riesgopropiedadvalors { get; set; }
	}
}
