
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the RIESGO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("RIESGO")]
	public partial class Riesgo
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [ForeignKey("RiesgoTipo")]
        public virtual string riesgoTipoid { get; set; }
	    public virtual string impacto { get; set; }
	    public virtual string probabilidad { get; set; }
	    public virtual string impactoMonto { get; set; }
	    public virtual string impactoTiempo { get; set; }
	    public virtual string gatillo { get; set; }
	    public virtual string consecuencia { get; set; }
	    public virtual string solucion { get; set; }
	    public virtual string riesgoSegundarios { get; set; }
	    public virtual string ejecutado { get; set; }
	    public virtual string fechaEjecucion { get; set; }
	    public virtual string resultado { get; set; }
	    public virtual string observaciones { get; set; }
	    [ForeignKey("Colaborador")]
        public virtual string colaboradorid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual Colaborador colaboradors { get; set; }
		public virtual RiesgoTipo riesgoTipos { get; set; }
		public virtual IEnumerable<Riesgo> riesgoes { get; set; }
	}
}
