
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the RIESGO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("RIESGO")]
	public partial class Riesgo
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    [Column("RIESGO_TIPOID")]
	    [ForeignKey("RiesgoTipo")]
        public virtual Int32 riesgoTipoid { get; set; }
	    public virtual decimal impacto { get; set; }
	    public virtual decimal probabilidad { get; set; }
	    [Column("IMPACTO_MONTO")]
	    public virtual decimal? impactoMonto { get; set; }
	    [Column("IMPACTO_TIEMPO")]
	    public virtual decimal? impactoTiempo { get; set; }
	    public virtual string gatillo { get; set; }
	    public virtual string consecuencia { get; set; }
	    public virtual string solucion { get; set; }
	    [Column("RIESGOS_SEGUNDARIOS")]
	    public virtual string riesgosSegundarios { get; set; }
	    public virtual Int32 ejecutado { get; set; }
	    [Column("FECHA_EJECUCION")]
	    public virtual DateTime? fechaEjecucion { get; set; }
	    public virtual string resultado { get; set; }
	    public virtual string observaciones { get; set; }
	    [ForeignKey("Colaborador")]
        public virtual Int32 colaboradorid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
		public virtual Colaborador colaboradors { get; set; }
		public virtual RiesgoTipo riesgoTipos { get; set; }
		public virtual IEnumerable<Riesgo> riesgoes { get; set; }
	}
}
