
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ROL_PERMISO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("ROL_PERMISO")]
	public partial class RolPermiso
	{
		[Key]
	    [ForeignKey("Rol")]
        public virtual string rolid { get; set; }
		[Key]
	    [ForeignKey("Permiso")]
        public virtual string permisoid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual Permiso permisos { get; set; }
		public virtual Rol rols { get; set; }
		public virtual IEnumerable<RolPermiso> rolpermisoes { get; set; }
	}
}
