
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the ROL_USUARIO_PROYECTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("ROL_USUARIO_PROYECTO")]
	public partial class RolUsuarioProyecto
	{
		[Key]
	    public virtual string rol { get; set; }
		[Key]
	    public virtual string proyecto { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	}
}
