
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the RTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("rtipo_propiedad")]
	public partial class rtipo_propiedad
	{
		[Key]
	    [ForeignKey("riesgo_tipo")]
        public virtual string riesgo_tipoid { get; set; }
		[Key]
	    [ForeignKey("riesgo_propiedad")]
        public virtual string riesgo_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual riesgo_propiedad riesgo_propiedads { get; set; }
		public virtual riesgo_tipo riesgo_tipos { get; set; }
		public virtual IEnumerable<rtipo_propiedad> rtipopropiedads { get; set; }
	}
}
