
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SCTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("sctipo_propiedad")]
	public partial class sctipo_propiedad
	{
		[Key]
	    [ForeignKey("subcomponente")]
        public virtual string subcomponente_tipoid { get; set; }
		[Key]
	    [ForeignKey("subcomponente_propiedad")]
        public virtual string subcomponente_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual subcomponente_propiedad subcomponente_propiedads { get; set; }
		public virtual subcomponente subcomponentes { get; set; }
		public virtual IEnumerable<sctipo_propiedad> sctipopropiedads { get; set; }
	}
}
