
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SCTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SCTIPO_PROPIEDAD")]
	public partial class SctipoPropiedad
	{
		[Key]
	    [ForeignKey("Subcomponente")]
        public virtual string subcomponenteTipoid { get; set; }
		[Key]
	    [ForeignKey("SubcomponentePropiedad")]
        public virtual string subcomponentePropiedadid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual SubcomponentePropiedad subcomponentePropiedads { get; set; }
		public virtual Subcomponente subcomponentes { get; set; }
		public virtual IEnumerable<SctipoPropiedad> sctipopropiedads { get; set; }
	}
}
