
 
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `EntityGenerator`
//     Provider:               `Oracle.ManagedDataAccess.Client`
//     Connection String:      `Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.128.128)(PORT=1521))(CONNECT_DATA=(SID=orcl)));User Id=sipro;Password=******;`
//     Include Views:          `True`

