
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `EntityGenerator`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=127.0.0.1;Port=3306;Database=sipro;Uid=root;Pwd=m1nf1n!`
//     Include Views:          `True`





