
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBCOMPONENTE_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("subcomponente_propiedad")]
	public partial class subcomponente_propiedad
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    [ForeignKey("dato_tipo")]
        public virtual string dato_tipoid { get; set; }
	    public virtual string estado { get; set; }
		public virtual dato_tipo dato_tipos { get; set; }
		public virtual IEnumerable<subcomponente_propiedad> subcomponentepropiedads { get; set; }
	}
}
