
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBCOMPONENTE_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("subcomponente_propiedad_valor")]
	public partial class subcomponente_propiedad_valor
	{
		[Key]
	    [ForeignKey("subcomponente")]
        public virtual string subcomponenteid { get; set; }
		[Key]
	    [ForeignKey("subcomponente_propiedad")]
        public virtual string subcomponente_propiedadid { get; set; }
	    public virtual string valor_string { get; set; }
	    public virtual string valor_entero { get; set; }
	    public virtual string valor_decimal { get; set; }
	    public virtual string valor_tiempo { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual subcomponente_propiedad subcomponente_propiedads { get; set; }
		public virtual subcomponente subcomponentes { get; set; }
		public virtual IEnumerable<subcomponente_propiedad_valor> subcomponentepropiedadvalors { get; set; }
	}
}
