
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBCOMPONENTE_USUARIO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SUBCOMPONENTE_USUARIO")]
	public partial class SubcomponenteUsuario
	{
		[Key]
	    [ForeignKey("Subcomponente")]
        public virtual Int32 subcomponenteid { get; set; }
		[Key]
	    public virtual string usuario { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual byte[] fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual byte[] fechaActualizacion { get; set; }
		public virtual Subcomponente subcomponentes { get; set; }
		public virtual IEnumerable<SubcomponenteUsuario> subcomponenteusuarios { get; set; }
	}
}
