
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODUCTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SUBPRODUCTO_PROPIEDAD_VALOR")]
	public partial class SubproductoPropiedadValor
	{
		[Key]
	    [ForeignKey("Subproducto")]
        public virtual string subproductoid { get; set; }
		[Key]
	    [ForeignKey("SubproductoPropiedad")]
        public virtual string subproductoPropiedadid { get; set; }
	    public virtual string valorEntero { get; set; }
	    public virtual string valorString { get; set; }
	    public virtual string valorDecimal { get; set; }
	    public virtual string valorTiempo { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
		public virtual Subproducto subproductos { get; set; }
		public virtual IEnumerable<SubproductoPropiedadValor> subproductopropiedadvalors { get; set; }
	}
}
