
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("subprodtipo_propiedad")]
	public partial class subprodtipo_propiedad
	{
		[Key]
	    [ForeignKey("subproducto_tipo")]
        public virtual string subproducto_tipoid { get; set; }
		[Key]
	    [ForeignKey("subproducto_propiedad")]
        public virtual string subproducto_propiedadid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
		public virtual subproducto_propiedad subproducto_propiedads { get; set; }
		public virtual subproducto_tipo subproducto_tipos { get; set; }
		public virtual IEnumerable<subprodtipo_propiedad> subprodtipopropiedads { get; set; }
	}
}
