
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SUBPRODTIPO_PROPIEDAD")]
	public partial class SubprodtipoPropiedad
	{
		[Key]
	    [ForeignKey("SubproductoTipo")]
        public virtual string subproductoTipoid { get; set; }
		[Key]
	    [ForeignKey("SubproductoPropiedad")]
        public virtual string subproductoPropiedadid { get; set; }
	    public virtual string usuarioCreo { get; set; }
	    public virtual string usuarioActualizo { get; set; }
	    public virtual string fechaCreacion { get; set; }
	    public virtual string fechaActualizacion { get; set; }
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
		public virtual SubproductoTipo subproductoTipos { get; set; }
		public virtual IEnumerable<SubprodtipoPropiedad> subprodtipopropiedads { get; set; }
	}
}
