
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODUCTO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("subproducto")]
	public partial class subproducto
	{
		[Key]
	    public virtual string id { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string descripcion { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string snip { get; set; }
	    public virtual string programa { get; set; }
	    public virtual string subprograma { get; set; }
	    public virtual string proyecto { get; set; }
	    public virtual string actividad { get; set; }
	    public virtual string obra { get; set; }
	    [ForeignKey("producto")]
        public virtual string productoid { get; set; }
	    [ForeignKey("subproducto_tipo")]
        public virtual string subproducto_tipoid { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string ueunidad_ejecutora { get; set; }
	    public virtual string latitud { get; set; }
	    public virtual string longitud { get; set; }
	    public virtual string costo { get; set; }
	    [ForeignKey("acumulacion_costo")]
        public virtual string acumulacion_costoid { get; set; }
	    public virtual string renglon { get; set; }
	    public virtual string ubicacion_geografica { get; set; }
	    public virtual string fecha_inicio { get; set; }
	    public virtual string fecha_fin { get; set; }
	    public virtual string duracion { get; set; }
	    public virtual string duracion_dimension { get; set; }
	    public virtual string orden { get; set; }
	    public virtual string treepath { get; set; }
	    public virtual string nivel { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string ejercicio { get; set; }
	    [ForeignKey("unidad_ejecutora")]
        public virtual string entidad { get; set; }
	    public virtual string fecha_inicio_real { get; set; }
	    public virtual string fecha_fin_real { get; set; }
	    public virtual string inversion_nueva { get; set; }
		public virtual acumulacion_costo acumulacion_costos { get; set; }
		public virtual unidad_ejecutora unidad_ejecutoras { get; set; }
		public virtual subproducto_tipo subproducto_tipos { get; set; }
		public virtual producto productos { get; set; }
		public virtual IEnumerable<subproducto> subproductoes { get; set; }
	}
}
