
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODTIPO_PROPIEDAD table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SUBPRODTIPO_PROPIEDAD")]
	public partial class SubprodtipoPropiedad
	{
		[Key]
	    [Column("SUBPRODUCTO_TIPOID")]
	    [ForeignKey("SubproductoTipo")]
        public virtual Int32 subproductoTipoid { get; set; }
		[Key]
	    [Column("SUBPRODUCTO_PROPIEDADID")]
	    [ForeignKey("SubproductoPropiedad")]
        public virtual Int32 subproductoPropiedadid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
<<<<<<< Updated upstream
		public virtual SubproductoTipo subproductoTipos { get; set; }
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
=======
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
		public virtual SubproductoTipo subproductoTipos { get; set; }
>>>>>>> Stashed changes
		public virtual IEnumerable<SubprodtipoPropiedad> subprodtipopropiedads { get; set; }
	}
}
