
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the SUBPRODUCTO_PROPIEDAD_VALOR table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("SUBPRODUCTO_PROPIEDAD_VALOR")]
	public partial class SubproductoPropiedadValor
	{
		[Key]
	    [ForeignKey("Subproducto")]
        public virtual Int32 subproductoid { get; set; }
		[Key]
	    [Column("SUBPRODUCTO_PROPIEDADID")]
	    [ForeignKey("SubproductoPropiedad")]
        public virtual Int32 subproductoPropiedadid { get; set; }
	    [Column("VALOR_ENTERO")]
	    public virtual Int32? valorEntero { get; set; }
	    [Column("VALOR_STRING")]
	    public virtual string valorString { get; set; }
	    [Column("VALOR_DECIMAL")]
	    public virtual decimal? valorDecimal { get; set; }
	    [Column("VALOR_TIEMPO")]
	    public virtual DateTime? valorTiempo { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual DateTime fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual DateTime? fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
<<<<<<< Updated upstream
		public virtual Subproducto subproductos { get; set; }
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
=======
		public virtual SubproductoPropiedad subproductoPropiedads { get; set; }
		public virtual Subproducto subproductos { get; set; }
>>>>>>> Stashed changes
		public virtual IEnumerable<SubproductoPropiedadValor> subproductopropiedadvalors { get; set; }
	}
}
