
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the TIPO_ADQUISICION table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("tipo_adquisicion")]
	public partial class tipo_adquisicion
	{
		[Key]
	    public virtual string id { get; set; }
	    [ForeignKey("cooperante")]
        public virtual string cooperantecodigo { get; set; }
	    [ForeignKey("cooperante")]
        public virtual string cooperanteejercicio { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
	    public virtual string convenio_cdirecta { get; set; }
		public virtual cooperante cooperantes { get; set; }
		public virtual IEnumerable<tipo_adquisicion> tipoadquisicions { get; set; }
	}
}
