
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the UNIDAD_EJECUTORA table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("UNIDAD_EJECUTORA")]
	public partial class UnidadEjecutora
	{
		[Key]
	    public virtual string unidadEjecutora { get; set; }
	    public virtual string nombre { get; set; }
		[Key]
	    [ForeignKey("Entidad")]
        public virtual string entidadentidad { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
		public virtual Entidad entidads { get; set; }
		public virtual IEnumerable<UnidadEjecutora> unidadejecutoras { get; set; }
	}
}
