
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the UNIDAD_EJECUTORA table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("unidad_ejecutora")]
	public partial class unidad_ejecutora
	{
		[Key]
	    public virtual string unidad_ejecutora { get; set; }
	    public virtual string nombre { get; set; }
		[Key]
	    [ForeignKey("entidad")]
        public virtual string entidadentidad { get; set; }
		[Key]
	    public virtual string ejercicio { get; set; }
		public virtual entidad entidads { get; set; }
		public virtual IEnumerable<unidad_ejecutora> unidadejecutoras { get; set; }
	}
}
