
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the USUARIO_PERMISO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("USUARIO_PERMISO")]
	public partial class UsuarioPermiso
	{
		[Key]
	    [ForeignKey("Usuario")]
        public virtual string usuariousuario { get; set; }
		[Key]
	    [ForeignKey("Permiso")]
        public virtual Int64 permisoid { get; set; }
	    [Column("USUARIO_CREO")]
	    public virtual string usuarioCreo { get; set; }
	    [Column("USUARIO_ACTUALIZO")]
	    public virtual string usuarioActualizo { get; set; }
	    [Column("FECHA_CREACION")]
	    public virtual byte[] fechaCreacion { get; set; }
	    [Column("FECHA_ACTUALIZACION")]
	    public virtual byte[] fechaActualizacion { get; set; }
	    public virtual Int32 estado { get; set; }
		public virtual Permiso permisos { get; set; }
		public virtual Usuario usuarios { get; set; }
		public virtual IEnumerable<UsuarioPermiso> usuariopermisoes { get; set; }
	}
}
