
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the USUARIO_PERMISO table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("usuario_permiso")]
	public partial class usuario_permiso
	{
		[Key]
	    [ForeignKey("usuario")]
        public virtual string usuariousuario { get; set; }
		[Key]
	    [ForeignKey("permiso")]
        public virtual string permisoid { get; set; }
	    public virtual string usuario_creo { get; set; }
	    public virtual string usuario_actualizo { get; set; }
	    public virtual string fecha_creacion { get; set; }
	    public virtual string fecha_actualizacion { get; set; }
	    public virtual string estado { get; set; }
		public virtual permiso permisos { get; set; }
		public virtual usuario usuarios { get; set; }
		public virtual IEnumerable<usuario_permiso> usuariopermisoes { get; set; }
	}
}
