
namespace SiproModel.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the USUARIO_LOG table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("USUARIO_LOG")]
	public partial class UsuarioLog
	{
	    public virtual string usuario { get; set; }
	    public virtual string fecha { get; set; }
	}
}
