export class Componente{
    id: number;
    nombre : string;
    descripcion : string;
    usuarioCreo : string;
    usuarioActualizo : string;
    fechaCreacion : string;
    fechaActualizacion : string;
    componenteTipoid: number;
    componentetiponombre : string;
    estado: number;
    snip: number;
    programa: number;
    subprograma: number;
    proyecto: number;
    obra: number;
    actividad: number;
    renglon: number;
    ubicacionGeografica: number;
    duracion: number;
    duracionDimension : string;
    fechaInicio : string;
    fechaFin : string;
    ueunidadEjecutora: number;
    ejercicio: number;
    entidad: number;
    unidadejecutoranombre : string;
    entidadnombre : string;
    latitud : string;
    longitud : string;
    costo: number;
    acumulacionCostoid: number;
    acumulacionCostoNombre : string;
    fuentePrestamo: number;
    fuenteDonacion: number;
    fuenteNacional: number;
    tieneHijos: boolean;
    esDeSigade: boolean;
    prestamoId: number;
    fechaInicioReal : string;
    fechaFinReal : string;
    inversionNueva: number;
    proyectoid: number;
    orden: number;
    treepath: string;
    nivel: number;
    componenteSigadeid: number;

    pagosPlanificados: string;
}