using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SPrestamoTipo.Controllers
{
    /// <summary>
    /// A class which represents the PrestamoTipoValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class PrestamoTipoValidator : AbstractValidator<JObject>
	{
		public PrestamoTipoValidator() 
		{
			RuleFor(prestamo_tipo => prestamo_tipo["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((prestamo_tipo, type) => { return GenericValidatorType.ValidateType(prestamo_tipo["nombre"].ToString(), typeof(String)); }).MaximumLength(1000);
			RuleFor(prestamo_tipo => prestamo_tipo["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((prestamo_tipo, type) => { return GenericValidatorType.ValidateType(prestamo_tipo["descripcion"].ToString(), typeof(String)); }).MaximumLength(2000);		
			
		}
	}
}
