using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProducto.Controllers
{
    /// <summary>
    /// A class which represents the ProductoValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class ProductoValidator : AbstractValidator<JObject>
	{
		public ProductoValidator() 
		{
			//RuleFor(producto => producto["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
			RuleFor(producto => producto["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			RuleFor(producto => producto["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(4000);
			RuleFor(producto => producto["componenteid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'componenteid' to type " + typeof(Int32));
			RuleFor(producto => producto["subcomponenteid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'subcomponenteid' to type " + typeof(Int32));
			//RuleFor(producto => producto["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto => producto["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto => producto["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(producto => producto["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			RuleFor(producto => producto["productoTipoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'productoTipoid' to type " + typeof(Int32));
			//RuleFor(producto => producto["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			RuleFor(producto => producto["ueunidadEjecutora"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'ueunidadEjecutora' to type " + typeof(Int32));
			RuleFor(producto => producto["snip"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'snip' to type " + typeof(Int32));
			RuleFor(producto => producto["programa"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'programa' to type " + typeof(Int32));
			RuleFor(producto => producto["subprograma"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'subprograma' to type " + typeof(Int32));
			RuleFor(producto => producto["proyecto"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'proyecto' to type " + typeof(Int32));
			RuleFor(producto => producto["actividad"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'actividad' to type " + typeof(Int32));
			RuleFor(producto => producto["obra"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'obra' to type " + typeof(Int32));
			RuleFor(producto => producto["latitud"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'latitud' to type " + typeof(String)).MaximumLength(30);
			RuleFor(producto => producto["longitud"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'longitud' to type " + typeof(String)).MaximumLength(30);
			RuleFor(producto => producto["peso"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'peso' to type " + typeof(Int32));
			RuleFor(producto => producto["costo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(decimal)); }).WithMessage("Error when trying to parse the property 'costo' to type " + typeof(decimal));
			RuleFor(producto => producto["acumulacionCostoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int64)); }).WithMessage("Error when trying to parse the property 'acumulacionCostoid' to type " + typeof(Int64));
			RuleFor(producto => producto["renglon"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'renglon' to type " + typeof(Int32));
			RuleFor(producto => producto["ubicacionGeografica"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'ubicacionGeografica' to type " + typeof(Int32));
			RuleFor(producto => producto["fechaInicio"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaInicio' to type " + typeof(DateTime));
			RuleFor(producto => producto["fechaFin"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaFin' to type " + typeof(DateTime));
			RuleFor(producto => producto["duracion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'duracion' to type " + typeof(Int32));
			RuleFor(producto => producto["duracionDimension"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'duracionDimension' to type " + typeof(String)).MaximumLength(1);
			//RuleFor(producto => producto["orden"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'orden' to type " + typeof(Int32));
			//RuleFor(producto => producto["treepath"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(String)); }).WithMessage("Error when trying to parse the property 'treepath' to type " + typeof(String)).MaximumLength(1000);
			//RuleFor(producto => producto["nivel"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'nivel' to type " + typeof(Int32));
			RuleFor(producto => producto["ejercicio"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'ejercicio' to type " + typeof(Int32));
			RuleFor(producto => producto["entidad"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'entidad' to type " + typeof(Int32));
			RuleFor(producto => producto["fechaInicioReal"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaInicioReal' to type " + typeof(DateTime));
			RuleFor(producto => producto["fechaFinReal"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaFinReal' to type " + typeof(DateTime));
			RuleFor(producto => producto["inversionNueva"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto => { return GenericValidatorType.ValidateType(producto, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'inversionNueva' to type " + typeof(Int32));
			
		}
	}
}
