using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProductoPropiedad.Controllers
{
    /// <summary>
    /// A class which represents the ProductoPropiedadValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class ProductoPropiedadValidator : AbstractValidator<JObject>
	{
		public ProductoPropiedadValidator() 
		{
			//RuleFor(producto_propiedad => producto_propiedad["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
			RuleFor(producto_propiedad => producto_propiedad["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			RuleFor(producto_propiedad => producto_propiedad["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(4000);
			//RuleFor(producto_propiedad => producto_propiedad["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto_propiedad => producto_propiedad["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto_propiedad => producto_propiedad["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(producto_propiedad => producto_propiedad["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			RuleFor(producto_propiedad => producto_propiedad["datoTipoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'datoTipoid' to type " + typeof(Int32));
			//RuleFor(producto_propiedad => producto_propiedad["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_propiedad => { return GenericValidatorType.ValidateType(producto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			
		}
	}
}
