
namespace SiproModelAnalyticCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the DTM_AVANCE_FISFINAN_ENP table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("DTM_AVANCE_FISFINAN_ENP")]
	public partial class DtmAvanceFisfinanEnp
	{
	    [Column("CODIGO_PRESUPUESTARIO")]
	    public virtual string codigoPresupuestario { get; set; }
	    [Column("EJERCICIO_FISCAL")]
	    public virtual Int32? ejercicioFiscal { get; set; }
	    [Column("ENTIDAD_PRESUPUESTARIA")]
	    public virtual Int32? entidadPresupuestaria { get; set; }
	    [Column("UNIDAD_EJECUTORA")]
	    public virtual Int32? unidadEjecutora { get; set; }
	}
}
