
namespace SiproModelAnalyticCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_EJECUCION_PRESUPUESTARIA table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_EJECUCION_PRESUPUESTARIA")]
	public partial class MvEjecucionPresupuestaria
	{
	    public virtual Int32? ejercicio { get; set; }
	    public virtual Int32? mes { get; set; }
	    public virtual Int32? entidad { get; set; }
	    [Column("UNIDAD_EJECUTORA")]
	    public virtual Int32? unidadEjecutora { get; set; }
	    public virtual Int32? programa { get; set; }
	    public virtual Int32? subprograma { get; set; }
	    public virtual Int32? proyecto { get; set; }
	    public virtual Int32? actividad { get; set; }
	    public virtual Int32? obra { get; set; }
	    public virtual Int32? renglon { get; set; }
	    [Column("RENGLON_NOMBRE")]
	    public virtual string renglonNombre { get; set; }
	    public virtual Int32? fuente { get; set; }
	    public virtual Int32? grupo { get; set; }
	    [Column("GRUPO_NOMBRE")]
	    public virtual string grupoNombre { get; set; }
	    public virtual Int32? subgrupo { get; set; }
	    [Column("SUBGRUPO_NOMBRE")]
	    public virtual string subgrupoNombre { get; set; }
	    [Column("EJECUCION_PRESUPUESTARIA")]
	    public virtual decimal? ejecucionPresupuestaria { get; set; }
	    public virtual Int32? organismo { get; set; }
	    public virtual Int32? correlativo { get; set; }
	    public virtual Int32? geografico { get; set; }
	}
}
