
namespace SiproModelAnalyticCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_EP_ESTRUCTURA table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_EP_ESTRUCTURA")]
	public partial class MvEpEstructura
	{
	    public virtual Int32? ejercicio { get; set; }
	    public virtual Int32? fuente { get; set; }
	    public virtual Int32? organismo { get; set; }
	    public virtual Int32? correlativo { get; set; }
	    public virtual Int32? programa { get; set; }
	    public virtual Int32? subprograma { get; set; }
	    public virtual Int32? proyecto { get; set; }
	    public virtual Int32? actividad { get; set; }
	    public virtual Int32? obra { get; set; }
	    public virtual Int32? renglon { get; set; }
	    public virtual Int32? geografico { get; set; }
	    public virtual decimal? enero { get; set; }
	    public virtual decimal? febrero { get; set; }
	    public virtual decimal? marzo { get; set; }
	    public virtual decimal? abril { get; set; }
	    public virtual decimal? mayo { get; set; }
	    public virtual decimal? junio { get; set; }
	    public virtual decimal? julio { get; set; }
	    public virtual decimal? agosto { get; set; }
	    public virtual decimal? septiembre { get; set; }
	    public virtual decimal? octubre { get; set; }
	    public virtual decimal? noviembre { get; set; }
	    public virtual decimal? diciembre { get; set; }
	}
}
