
namespace SiproModelAnalyticCore.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_GC_ADQUISICIONES table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_GC_ADQUISICIONES")]
	public partial class MvGcAdquisiciones
	{
	    public virtual Int32? nog { get; set; }
	    [Column("NUMERO_CONTRATO")]
	    public virtual string numeroContrato { get; set; }
	    [Column("MONTO_CONTRATO")]
	    public virtual decimal? montoContrato { get; set; }
	    [Column("PREPARACION_DOCUMENTOS")]
	    public virtual DateTime? preparacionDocumentos { get; set; }
	    [Column("LANZAMIENTO_EVENTO")]
	    public virtual DateTime? lanzamientoEvento { get; set; }
	    [Column("RECEPCION_OFERTAS")]
	    public virtual DateTime? recepcionOfertas { get; set; }
	    public virtual DateTime? adjudicacion { get; set; }
	    [Column("FIRMA_CONTRATO")]
	    public virtual DateTime? firmaContrato { get; set; }
	}
}
