using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProductoTipo.Controllers
{
    /// <summary>
    /// A class which represents the ProductoTipoValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class ProductoTipoValidator : AbstractValidator<JObject>
	{
		public ProductoTipoValidator() 
		{
			//RuleFor(producto_tipo => producto_tipo["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
			RuleFor(producto_tipo => producto_tipo["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			RuleFor(producto_tipo => producto_tipo["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(2000);
			//RuleFor(producto_tipo => producto_tipo["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto_tipo => producto_tipo["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(producto_tipo => producto_tipo["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(producto_tipo => producto_tipo["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			//RuleFor(producto_tipo => producto_tipo["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(producto_tipo => { return GenericValidatorType.ValidateType(producto_tipo, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			
		}
	}
}
