using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SEntidad.Controllers
{
    /// <summary>
    /// A class which represents the EntidadValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class EntidadValidator : AbstractValidator<JObject>
	{
		public EntidadValidator() 
		{
			RuleFor(entidad => entidad["entidad"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((entidad, type) => { return GenericValidatorType.ValidateType(entidad["entidad"].ToString(), typeof(Int32)); });
			RuleFor(entidad => entidad["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((entidad, type) => { return GenericValidatorType.ValidateType(entidad["nombre"].ToString(), typeof(String)); }).MaximumLength(1000);
			RuleFor(entidad => entidad["abreviatura"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((entidad, type) => { return GenericValidatorType.ValidateType(entidad["abreviatura"].ToString(), typeof(String)); }).MaximumLength(100);
			RuleFor(entidad => entidad["ejercicio"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((entidad, type) => { return GenericValidatorType.ValidateType(entidad["ejercicio"].ToString(), typeof(Int32)); });
			
		}
	}
}
