using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProyecto.Controllers
{
    /// <summary>
    /// A class which represents the LineaBaseValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class LineaBaseValidator : AbstractValidator<JObject>
	{
		public LineaBaseValidator() 
		{
			RuleFor(linea_base => linea_base["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((linea_base, type) => { return GenericValidatorType.ValidateType(linea_base["nombre"].ToString(), typeof(String)); }).MaximumLength(100);
			RuleFor(linea_base => linea_base["tipoLineaBase"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((linea_base, type) => { return GenericValidatorType.ValidateType(linea_base["tipoLineaBase"].ToString(), typeof(Int32)); });			
			
		}
	}
}
