using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProyecto.Controllers
{
    /// <summary>
    /// A class which represents the PepDetalleValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class PepDetalleValidator : AbstractValidator<JObject>
	{
		public PepDetalleValidator() 
		{
			RuleFor(pep_detalle => pep_detalle["proyectoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["proyectoid"].ToString(), typeof(Int32)); });
			RuleFor(pep_detalle => pep_detalle["observaciones"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["observaciones"].ToString(), typeof(String)); }).MaximumLength(4000);
			RuleFor(pep_detalle => pep_detalle["alertivos"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["alertivos"].ToString(), typeof(String)); }).MaximumLength(4000);
			RuleFor(pep_detalle => pep_detalle["elaborado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["elaborado"].ToString(), typeof(String)); }).MaximumLength(100);
			RuleFor(pep_detalle => pep_detalle["aprobado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["aprobado"].ToString(), typeof(String)); }).MaximumLength(100);
			RuleFor(pep_detalle => pep_detalle["autoridad"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((pep_detalle, type) => { return GenericValidatorType.ValidateType(pep_detalle["autoridad"].ToString(), typeof(String)); }).MaximumLength(100);			

		}
	}
}
