using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SProyectoPropiedad.Controllers
{
    /// <summary>
    /// A class which represents the ProyectoPropiedadValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class ProyectoPropiedadValidator : AbstractValidator<JObject>
	{
		public ProyectoPropiedadValidator() 
		{
			//RuleFor(proyecto_propiedad => proyecto_propiedad["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
			RuleFor(proyecto_propiedad => proyecto_propiedad["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			RuleFor(proyecto_propiedad => proyecto_propiedad["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(2000);
			//RuleFor(proyecto_propiedad => proyecto_propiedad["datoTipoid"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'datoTipoid' to type " + typeof(Int32));
			//RuleFor(proyecto_propiedad => proyecto_propiedad["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(proyecto_propiedad => proyecto_propiedad["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(proyecto_propiedad => proyecto_propiedad["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(proyecto_propiedad => proyecto_propiedad["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			//RuleFor(proyecto_propiedad => proyecto_propiedad["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(proyecto_propiedad => { return GenericValidatorType.ValidateType(proyecto_propiedad, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			
		}
	}
}
