
namespace SiproModelAnalytic.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the DTM_AVANCE_FISFINAN_DTI table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("DTM_AVANCE_FISFINAN_DTI")]
	public partial class DtmAvanceFisfinanDti
	{
	    [Column("FECHA_CORTE")]
	    public virtual DateTime? fechaCorte { get; set; }
	    [Column("NO_PRESTAMO")]
	    public virtual string noPrestamo { get; set; }
	    [Column("CODIGO_PRESUPUESTARIO")]
	    public virtual string codigoPresupuestario { get; set; }
	    [Column("NOMBRE_PROGRAMA")]
	    public virtual string nombrePrograma { get; set; }
	    [Column("CODIGO_ORGANISMO_FINAN")]
	    public virtual Int32? codigoOrganismoFinan { get; set; }
	    [Column("SIGLAS_ORGANISMO_FINAN")]
	    public virtual string siglasOrganismoFinan { get; set; }
	    [Column("NOMBRE_ORGANISMO_FINAN")]
	    public virtual string nombreOrganismoFinan { get; set; }
	    [Column("MONEDA_PRESTAMO")]
	    public virtual string monedaPrestamo { get; set; }
	    [Column("MONTO_CONTRATADO")]
	    public virtual decimal? montoContratado { get; set; }
	    [Column("MONTO_CONTRATADO_USD")]
	    public virtual decimal? montoContratadoUsd { get; set; }
	    [Column("MONTO_CONTRATADO_GTQ")]
	    public virtual decimal? montoContratadoGtq { get; set; }
	    public virtual decimal? desembolsos { get; set; }
	    [Column("DESEMBOLSOS_USD")]
	    public virtual decimal? desembolsosUsd { get; set; }
	    [Column("DESEMBOLSOS_GTQ")]
	    public virtual decimal? desembolsosGtq { get; set; }
	    [Column("FECHA_DECRETO")]
	    public virtual DateTime? fechaDecreto { get; set; }
	    [Column("FECHA_SUSCRIPCION")]
	    public virtual DateTime? fechaSuscripcion { get; set; }
	    [Column("FECHA_VIGENCIA")]
	    public virtual DateTime? fechaVigencia { get; set; }
	    [Column("POR_DESEMBOLSAR")]
	    public virtual decimal? porDesembolsar { get; set; }
	    [Column("POR_DESEMBOLSAR_USD")]
	    public virtual decimal? porDesembolsarUsd { get; set; }
	    [Column("POR_DESEMBOLSAR_GTQ")]
	    public virtual decimal? porDesembolsarGtq { get; set; }
	    [Column("ESTADO_PRESTAMO")]
	    public virtual string estadoPrestamo { get; set; }
	    public virtual string objetivo { get; set; }
	}
}
