
namespace SiproModelAnalytic.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_EP_EJEC_ASIG_VIGE table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_EP_EJEC_ASIG_VIGE")]
	public partial class MvEpEjecAsigVige
	{
	    public virtual Int32 ejercicio { get; set; }
	    public virtual Int32? mes { get; set; }
	    public virtual Int32? entidad { get; set; }
	    [Column("UNIDAD_EJECUTRA")]
	    public virtual Int32? unidadEjecutra { get; set; }
	    public virtual Int32? programa { get; set; }
	    public virtual Int32? subprograma { get; set; }
	    public virtual Int32? proyecto { get; set; }
	    public virtual Int32? actividad { get; set; }
	    public virtual Int32? obra { get; set; }
	    public virtual Int32? renglon { get; set; }
	    public virtual Int32? geografico { get; set; }
	    public virtual Int32? correlativo { get; set; }
	    public virtual Int32? organismo { get; set; }
	    public virtual Int32? fuente { get; set; }
	    public virtual decimal? ejecutado { get; set; }
	    public virtual decimal? asignado { get; set; }
	    public virtual decimal? modificaciones { get; set; }
	}
}
