
namespace SiproModelAnalytic.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_EP_METAS table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_EP_METAS")]
	public partial class MvEpMetas
	{
		[Key]
	    public virtual Int32 id { get; set; }
	    public virtual Int32 ejercicio { get; set; }
	    [Column("OBJETO_ID")]
	    public virtual Int32 objetoId { get; set; }
	    [Column("OBJETO_TIPO")]
	    public virtual Int64 objetoTipo { get; set; }
	    [Column("META_UNIDAD_MEDIDAID")]
	    public virtual Int32 metaUnidadMedidaid { get; set; }
	    public virtual decimal? enerop { get; set; }
	    public virtual decimal? eneror { get; set; }
	    public virtual decimal? febrerop { get; set; }
	    public virtual decimal? febreror { get; set; }
	    public virtual decimal? marzop { get; set; }
	    public virtual decimal? marzor { get; set; }
	    public virtual decimal? abrilp { get; set; }
	    public virtual decimal? abrilr { get; set; }
	    public virtual decimal? mayop { get; set; }
	    public virtual decimal? mayor { get; set; }
	    public virtual decimal? juniop { get; set; }
	    public virtual decimal? junior { get; set; }
	    public virtual decimal? juliop { get; set; }
	    public virtual decimal? julior { get; set; }
	    public virtual decimal? agostop { get; set; }
	    public virtual decimal? agostor { get; set; }
	    public virtual decimal? septiembrep { get; set; }
	    public virtual decimal? septiembrer { get; set; }
	    public virtual decimal? octubrep { get; set; }
	    public virtual decimal? octubrer { get; set; }
	    public virtual decimal? noviembrep { get; set; }
	    public virtual decimal? noviembrer { get; set; }
	    public virtual decimal? diciembrep { get; set; }
	    public virtual decimal? diciembrer { get; set; }
	    public virtual decimal? lineabase { get; set; }
	    public virtual decimal? metafinal { get; set; }
	}
}
