
namespace SiproModelAnalytic.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the MV_PR_ESTRUCTURA table.
	/// Generated by SIPRO TEAM. April 2018. 
    /// </summary>
	[Table("MV_PR_ESTRUCTURA")]
	public partial class MvPrEstructura
	{
		[Key]
	    public virtual Int64 id { get; set; }
	    [Column("OBJETO_ID")]
	    public virtual Int32? objetoId { get; set; }
	    [Column("OBJETO_TIPO")]
	    public virtual Int32? objetoTipo { get; set; }
	    public virtual string nombre { get; set; }
	    public virtual Int32? fuente { get; set; }
	    public virtual Int32? organismo { get; set; }
	    public virtual Int32? correlativo { get; set; }
	    public virtual Int32? programa { get; set; }
	    public virtual Int32? subprograma { get; set; }
	    public virtual Int32? proyecto { get; set; }
	    public virtual Int32? actividad { get; set; }
	    public virtual Int32? obra { get; set; }
	    [Column("OBJETO_ID_PADRE")]
	    public virtual Int32? objetoIdPadre { get; set; }
	    [Column("OBJETO_TIPO_PADRE")]
	    public virtual Int32? objetoTipoPadre { get; set; }
	}
}
