/* ------- Selects --------*/

SELECT id, nombre, descripcion, fecha_inicio, fecha_fin, porcentaje_avance, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, actividad_tipoid, snip, programa, subprograma, proyecto, actividad, obra, objeto_id, objeto_tipo, duracion, duracion_dimension, pred_objeto_id, pred_objeto_tipo, latitud, longitud, costo, acumulacion_costo, renglon, ubicacion_geografica, orden, treePath, nivel, proyecto_base, componente_base, producto_base, fecha_inicio_real, fecha_fin_real, inversion_nueva FROM actividad;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid FROM actividad_propiedad;
SELECT actividadid, actividad_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM actividad_propiedad_valor;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM actividad_tipo;
SELECT actividadid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM actividad_usuario;
SELECT id, nombre, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM acumulacion_costo;
SELECT id, matriz_raciid, colaboradorid, rol_raci, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM asignacion_raci;
SELECT actividad_tipoid, actividad_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM atipo_propiedad;
SELECT id, nombre, descripcion FROM autorizacion_tipo;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM categoria_adquisicion;
SELECT id, pnombre, snombre, papellido, sapellido, cui, ueunidad_ejecutora, usuariousuario, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, ejercicio, entidad FROM colaborador;
SELECT id, nombre, descripcion, proyectoid, componente_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treepath, nivel, ejercicio, entidad, es_de_sigade, fuente_prestamo, fuente_donacion, fuente_nacional, componente_sigadeid, fecha_inicio_real, fecha_fin_real, inversion_nueva FROM componente;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado FROM componente_propiedad;
SELECT componenteid, componente_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM componente_propiedad_valor;
SELECT id, nombre, codigo_presupuestario, numero_componente, monto_componente, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM componente_sigade;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM componente_tipo;
SELECT componenteid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM componente_usuario;
SELECT codigo, siglas, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ejercicio FROM cooperante;
SELECT componente_tipoid, componente_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM ctipo_propiedad;
SELECT id, nombre, descripcion FROM dato_tipo;
SELECT id, fecha, estado, monto, tipo_cambio, monto_moneda_origen, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, proyectoid, desembolso_tipoid, tipo_monedaid FROM desembolso;
SELECT id, nombre, descripcion, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM desembolso_tipo;
SELECT id, nombre, extension, id_tipo_objeto, id_objeto, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM documento;
SELECT id, nombre, descripcion FROM ejecucion_estado;
SELECT entidad, nombre, abreviatura, ejercicio FROM entidad;
SELECT id, nombre, valor FROM estado;
SELECT usuario, tabla, valores FROM estado_tabla;
SELECT id, nombre, descripcion, proyecto, color_principal, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM etiqueta;
SELECT id, codigo, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, formulario_tipoid FROM formulario;
SELECT id, texto, formularioid, orden, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion, estado, formulario_item_tipoid FROM formulario_item;
SELECT id, formulario_itemid, etiqueta, valor_entero, valor_string, valor_tiempo, valor_decimal, estado, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion FROM formulario_item_opcion;
SELECT id, nombre, descripcion, estado, usuario_creo, fecha_creacion, usuario_actualizacion, fecha_actualizacion, dato_tipoid FROM formulario_item_tipo;
SELECT formulario_itemid, objeto_formularioformularioid, objeto_formularioobjeto_tipoid, valor_entero, valor_string, valor_tiempo, valor_decimal, proyectoid, componenteid, productoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, objeto_formularioobjeto_id FROM formulario_item_valor;
SELECT id, nombre, descripcion, usario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM formulario_tipo;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, fecha, proyectoid, hito_tipoid FROM hito;
SELECT id, valor_entero, valor_string, valor_decimal, valor_tiempo, comentario, hitoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM hito_resultado;
SELECT id, nombre, descripcion, estado, dato_tipoid, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion FROM hito_tipo;
SELECT id, nombre, descripcion FROM interes_tipo;
SELECT id, nombre, proyectoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, tipo_linea_base, sobreescribir FROM linea_base;
SELECT id, proyectoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM matriz_raci;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, meta_unidad_medidaid, dato_tipoid, objeto_id, objeto_tipo, meta_final_entero, meta_final_string, meta_final_decimal, meta_final_fecha FROM meta;
SELECT metaid, fecha, usuario, valor_entero, valor_string, valor_decimal, valor_tiempo, estado, fecha_ingreso FROM meta_avance;
SELECT metaid, ejercicio, enero_entero, enero_string, enero_decimal, enero_tiempo, febrero_entero, febrero_string, febrero_decimal, febrero_tiempo, marzo_entero, marzo_string, marzo_decimal, marzo_tiempo, abril_entero, abril_string, abril_decimal, abril_tiempo, mayo_entero, mayo_string, mayo_decimal, mayo_tiempo, junio_entero, junio_string, junio_decimal, junio_tiempo, julio_entero, julio_string, julio_decimal, julio_tiempo, agosto_entero, agosto_string, agosto_decimal, agosto_tiempo, septiembre_entero, septiembre_string, septiembre_decimal, septiembre_tiempo, octubre_entero, octubre_string, octubre_decimal, octubre_tiempo, noviembre_entero, noviembre_string, noviembre_decimal, noviembre_tiempo, diciembre_entero, diciembre_string, diciembre_decimal, diciembre_tiempo, estado, usuario, fecha_ingreso FROM meta_planificado;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM meta_tipo;
SELECT id, nombre, descripcion, simbolo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM meta_unidad_medida;
SELECT metaid, fecha, usuario, valor_entero, valor_string, valor_decimal, valor_tiempo FROM meta_valor;
SELECT formularioid, objeto_tipo, objeto_id, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM objeto_formulario;
SELECT riesgoid, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM objeto_riesgo;
SELECT id, fecha_pago, pago, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM pago_planificado;
SELECT proyectoid, observaciones, alertivos, elaborado, aprobado, autoridad, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM pep_detalle;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM permiso;
SELECT id, tipo_adquisicion, categoria_adquisicion, unidad_medida, cantidad, total, precio_unitario, preparacion_doc_planificado, preparacion_doc_real, lanzamiento_evento_planificado, lanzamiento_evento_real, recepcion_ofertas_planificado, recepcion_ofertas_real, adjudicacion_planificado, adjudicacion_real, firma_contrato_planificado, firma_contrato_real, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, bloqueado, numero_contrato, monto_contrato, nog, tipo_revision FROM plan_adquisicion;
SELECT id, plan_adquisicionid, fecha_pago, pago, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM plan_adquisicion_pago;
SELECT id, fecha_corte, codigo_presupuestario, numero_prestamo, destino, sector_economico, ueunidad_ejecutora, fecha_firma, autorizacion_tipoid, numero_autorizacion, fecha_autorizacion, anios_plazo, anios_gracia, fecha_fin_ejecucion, perido_ejecucion, interes_tipoid, porcentaje_interes, porcentaje_comision_compra, tipo_monedaid, monto_contratado, amortizado, por_amortizar, principal_anio, intereses_anio, comision_compromiso_anio, otros_gastos, principal_acumulado, intereses_acumulados, comision_compromiso_acumulado, otros_cargos_acumulados, presupuesto_asignado_func, presupuesto_asignado_inv, presupuesto_modificado_func, presupuesto_modificado_inv, presupuesto_vigente_func, presupuesto_vigente_inv, presupuesto_devengado_func, presupuesto_devengado_inv, presupuesto_pagado_func, presupuesto_pagado_inv, saldo_cuentas, desembolsado_real, ejecucion_estadoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, proyecto_programa, fecha_decreto, fecha_suscripcion, fecha_elegibilidad_ue, fecha_cierre_origianl_ue, fecha_cierre_actual_ue, meses_prorroga_ue, plazo_ejecucion_ue, monto_asignado_ue, desembolso_a_fecha_ue, monto_por_desembolsar_ue, fecha_vigencia, monto_contratado_usd, monto_contratado_qtz, desembolso_a_fecha_usd, monto_por_desembolsar_usd, monto_asignado_ue_usd, monto_asignado_ue_qtz, desembolso_a_fecha_ue_usd, monto_por_desembolsar_ue_usd, entidad, ejercicio, objetivo, objetivo_especifico, porcentaje_avance, cooperantecodigo, cooperanteejercicio FROM prestamo;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM prestamo_tipo;
SELECT prestamoId, tipoPrestamoId, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM prestamo_tipo_prestamo;
SELECT prestamoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM prestamo_usuario;
SELECT producto_tipoid, producto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM prodtipo_propiedad;
SELECT id, nombre, descripcion, componenteid, subcomponenteid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, producto_tipoid, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, peso, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, fecha_inicio_real, fecha_fin_real, inversion_nueva FROM producto;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado FROM producto_propiedad;
SELECT producto_propiedadid, productoid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM producto_propiedad_valor;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM producto_tipo;
SELECT productoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM producto_usuario;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, proyecto_tipoid, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, objetivo, director_proyecto, enunciado_alcance, costo, acumulacion_costoid, objetivo_especifico, vision_general, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, ejecucion_fisica_real, proyecto_clase, project_cargado, prestamoid, observaciones, coordinador, fecha_elegibilidad, fecha_inicio_real, fecha_fin_real, congelado, fecha_cierre FROM proyecto;
SELECT id, proyectoid, entidadentidad, impacto, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, ejercicio FROM proyecto_impacto;
SELECT proyectoid, colaboradorid, estado, fecha_creacion, fecha_actualizacion, usuario_creo, usuario_actualizo FROM proyecto_miembro;
SELECT id, nombre, descripcion, dato_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM proyecto_propiedad;
SELECT proyectoid, proyecto_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM proyecto_propiedad_valor;
SELECT id, colaboradorid, proyectoid, rol_unidad_ejecutoraid, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM proyecto_rol_colaborador;
SELECT id, nombre, descripcion, usario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM proyecto_tipo;
SELECT proyectoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM proyecto_usuario;
SELECT proyecto_tipoid, proyecto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM ptipo_propiedad;
SELECT id, nombre, descripcion, riesgo_tipoid, impacto, probabilidad, impacto_monto, impacto_tiempo, gatillo, consecuencia, solucion, riesgos_segundarios, ejecutado, fecha_ejecucion, resultado, observaciones, colaboradorid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM riesgo;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid FROM riesgo_propiedad;
SELECT riesgoid, riesgo_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM riesgo_propiedad_valor;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM riesgo_tipo;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM rol;
SELECT rolid, permisoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM rol_permiso;
SELECT id, nombre, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, rol_predeterminado FROM rol_unidad_ejecutora;
SELECT rol, proyecto, usuario FROM rol_usuario_proyecto;
SELECT riesgo_tipoid, riesgo_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM rtipo_propiedad;
SELECT subcomponente_tipoid, subcomponente_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM sctipo_propiedad;
SELECT id, nombre, descripcion, componenteid, subcomponente_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, entidad, ejercicio, fecha_inicio_real, fecha_fin_real, inversion_nueva FROM subcomponente;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado FROM subcomponente_propiedad;
SELECT subcomponenteid, subcomponente_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM subcomponente_propiedad_valor;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM subcomponente_tipo;
SELECT subcomponenteid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM subcomponente_usuario;
SELECT subproducto_tipoid, subproducto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM subprodtipo_propiedad;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, snip, programa, subprograma, proyecto, actividad, obra, productoid, subproducto_tipoid, ueunidad_ejecutora, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, fecha_inicio_real, fecha_fin_real, inversion_nueva FROM subproducto;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid FROM subproducto_propiedad;
SELECT subproductoid, subproducto_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM subproducto_propiedad_valor;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM subproducto_tipo;
SELECT subproductoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion FROM subproducto_usuario;
SELECT id, cooperantecodigo, cooperanteejercicio, nombre, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, convenio_cdirecta FROM tipo_adquisicion;
SELECT id, nombre, simbolo FROM tipo_moneda;
SELECT unidad_ejecutora, nombre, entidadentidad, ejercicio FROM unidad_ejecutora;
SELECT id, nombre, descripcion, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion, estado FROM unidad_medida;
SELECT usuario, password, salt, email, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, sistema_usuario FROM usuario;
SELECT usuario, fecha FROM usuario_log;
SELECT usuariousuario, permisoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado FROM usuario_permiso;


/* ------- Inserts --------*/

INSERT INTO actividad(id, nombre, descripcion, fecha_inicio, fecha_fin, porcentaje_avance, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, actividad_tipoid, snip, programa, subprograma, proyecto, actividad, obra, objeto_id, objeto_tipo, duracion, duracion_dimension, pred_objeto_id, pred_objeto_tipo, latitud, longitud, costo, acumulacion_costo, renglon, ubicacion_geografica, orden, treePath, nivel, proyecto_base, componente_base, producto_base, fecha_inicio_real, fecha_fin_real, inversion_nueva) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO actividad_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO actividad_propiedad_valor(actividadid, actividad_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO actividad_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO actividad_usuario(actividadid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO acumulacion_costo(id, nombre, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO asignacion_raci(id, matriz_raciid, colaboradorid, rol_raci, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO atipo_propiedad(actividad_tipoid, actividad_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO autorizacion_tipo(id, nombre, descripcion) VALUES (?, ?, ?);
INSERT INTO categoria_adquisicion(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO colaborador(id, pnombre, snombre, papellido, sapellido, cui, ueunidad_ejecutora, usuariousuario, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, ejercicio, entidad) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente(id, nombre, descripcion, proyectoid, componente_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treepath, nivel, ejercicio, entidad, es_de_sigade, fuente_prestamo, fuente_donacion, fuente_nacional, componente_sigadeid, fecha_inicio_real, fecha_fin_real, inversion_nueva) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente_propiedad_valor(componenteid, componente_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente_sigade(id, nombre, codigo_presupuestario, numero_componente, monto_componente, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO componente_usuario(componenteid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO cooperante(codigo, siglas, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ejercicio) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO ctipo_propiedad(componente_tipoid, componente_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO dato_tipo(id, nombre, descripcion) VALUES (?, ?, ?);
INSERT INTO desembolso(id, fecha, estado, monto, tipo_cambio, monto_moneda_origen, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, proyectoid, desembolso_tipoid, tipo_monedaid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO desembolso_tipo(id, nombre, descripcion, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO documento(id, nombre, extension, id_tipo_objeto, id_objeto, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO ejecucion_estado(id, nombre, descripcion) VALUES (?, ?, ?);
INSERT INTO entidad(entidad, nombre, abreviatura, ejercicio) VALUES (?, ?, ?, ?);
INSERT INTO estado(id, nombre, valor) VALUES (?, ?, ?);
INSERT INTO estado_tabla(usuario, tabla, valores) VALUES (?, ?, ?);
INSERT INTO etiqueta(id, nombre, descripcion, proyecto, color_principal, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario(id, codigo, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, formulario_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario_item(id, texto, formularioid, orden, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion, estado, formulario_item_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario_item_opcion(id, formulario_itemid, etiqueta, valor_entero, valor_string, valor_tiempo, valor_decimal, estado, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario_item_tipo(id, nombre, descripcion, estado, usuario_creo, fecha_creacion, usuario_actualizacion, fecha_actualizacion, dato_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario_item_valor(formulario_itemid, objeto_formularioformularioid, objeto_formularioobjeto_tipoid, valor_entero, valor_string, valor_tiempo, valor_decimal, proyectoid, componenteid, productoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, objeto_formularioobjeto_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO formulario_tipo(id, nombre, descripcion, usario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO hito(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, fecha, proyectoid, hito_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO hito_resultado(id, valor_entero, valor_string, valor_decimal, valor_tiempo, comentario, hitoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO hito_tipo(id, nombre, descripcion, estado, dato_tipoid, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO interes_tipo(id, nombre, descripcion) VALUES (?, ?, ?);
INSERT INTO linea_base(id, nombre, proyectoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, tipo_linea_base, sobreescribir) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO matriz_raci(id, proyectoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, meta_unidad_medidaid, dato_tipoid, objeto_id, objeto_tipo, meta_final_entero, meta_final_string, meta_final_decimal, meta_final_fecha) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta_avance(metaid, fecha, usuario, valor_entero, valor_string, valor_decimal, valor_tiempo, estado, fecha_ingreso) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta_planificado(metaid, ejercicio, enero_entero, enero_string, enero_decimal, enero_tiempo, febrero_entero, febrero_string, febrero_decimal, febrero_tiempo, marzo_entero, marzo_string, marzo_decimal, marzo_tiempo, abril_entero, abril_string, abril_decimal, abril_tiempo, mayo_entero, mayo_string, mayo_decimal, mayo_tiempo, junio_entero, junio_string, junio_decimal, junio_tiempo, julio_entero, julio_string, julio_decimal, julio_tiempo, agosto_entero, agosto_string, agosto_decimal, agosto_tiempo, septiembre_entero, septiembre_string, septiembre_decimal, septiembre_tiempo, octubre_entero, octubre_string, octubre_decimal, octubre_tiempo, noviembre_entero, noviembre_string, noviembre_decimal, noviembre_tiempo, diciembre_entero, diciembre_string, diciembre_decimal, diciembre_tiempo, estado, usuario, fecha_ingreso) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta_unidad_medida(id, nombre, descripcion, simbolo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO meta_valor(metaid, fecha, usuario, valor_entero, valor_string, valor_decimal, valor_tiempo) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO objeto_formulario(formularioid, objeto_tipo, objeto_id, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO objeto_riesgo(riesgoid, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO pago_planificado(id, fecha_pago, pago, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO pep_detalle(proyectoid, observaciones, alertivos, elaborado, aprobado, autoridad, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO permiso(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO plan_adquisicion(id, tipo_adquisicion, categoria_adquisicion, unidad_medida, cantidad, total, precio_unitario, preparacion_doc_planificado, preparacion_doc_real, lanzamiento_evento_planificado, lanzamiento_evento_real, recepcion_ofertas_planificado, recepcion_ofertas_real, adjudicacion_planificado, adjudicacion_real, firma_contrato_planificado, firma_contrato_real, objeto_id, objeto_tipo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, bloqueado, numero_contrato, monto_contrato, nog, tipo_revision) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO plan_adquisicion_pago(id, plan_adquisicionid, fecha_pago, pago, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO prestamo(id, fecha_corte, codigo_presupuestario, numero_prestamo, destino, sector_economico, ueunidad_ejecutora, fecha_firma, autorizacion_tipoid, numero_autorizacion, fecha_autorizacion, anios_plazo, anios_gracia, fecha_fin_ejecucion, perido_ejecucion, interes_tipoid, porcentaje_interes, porcentaje_comision_compra, tipo_monedaid, monto_contratado, amortizado, por_amortizar, principal_anio, intereses_anio, comision_compromiso_anio, otros_gastos, principal_acumulado, intereses_acumulados, comision_compromiso_acumulado, otros_cargos_acumulados, presupuesto_asignado_func, presupuesto_asignado_inv, presupuesto_modificado_func, presupuesto_modificado_inv, presupuesto_vigente_func, presupuesto_vigente_inv, presupuesto_devengado_func, presupuesto_devengado_inv, presupuesto_pagado_func, presupuesto_pagado_inv, saldo_cuentas, desembolsado_real, ejecucion_estadoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, proyecto_programa, fecha_decreto, fecha_suscripcion, fecha_elegibilidad_ue, fecha_cierre_origianl_ue, fecha_cierre_actual_ue, meses_prorroga_ue, plazo_ejecucion_ue, monto_asignado_ue, desembolso_a_fecha_ue, monto_por_desembolsar_ue, fecha_vigencia, monto_contratado_usd, monto_contratado_qtz, desembolso_a_fecha_usd, monto_por_desembolsar_usd, monto_asignado_ue_usd, monto_asignado_ue_qtz, desembolso_a_fecha_ue_usd, monto_por_desembolsar_ue_usd, entidad, ejercicio, objetivo, objetivo_especifico, porcentaje_avance, cooperantecodigo, cooperanteejercicio) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO prestamo_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO prestamo_tipo_prestamo(prestamoId, tipoPrestamoId, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO prestamo_usuario(prestamoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO prodtipo_propiedad(producto_tipoid, producto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO producto(id, nombre, descripcion, componenteid, subcomponenteid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, producto_tipoid, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, peso, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, fecha_inicio_real, fecha_fin_real, inversion_nueva) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO producto_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO producto_propiedad_valor(producto_propiedadid, productoid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO producto_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO producto_usuario(productoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO proyecto(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, proyecto_tipoid, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, objetivo, director_proyecto, enunciado_alcance, costo, acumulacion_costoid, objetivo_especifico, vision_general, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, ejecucion_fisica_real, proyecto_clase, project_cargado, prestamoid, observaciones, coordinador, fecha_elegibilidad, fecha_inicio_real, fecha_fin_real, congelado, fecha_cierre) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_impacto(id, proyectoid, entidadentidad, impacto, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, ejercicio) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_miembro(proyectoid, colaboradorid, estado, fecha_creacion, fecha_actualizacion, usuario_creo, usuario_actualizo) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_propiedad(id, nombre, descripcion, dato_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_propiedad_valor(proyectoid, proyecto_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_rol_colaborador(id, colaboradorid, proyectoid, rol_unidad_ejecutoraid, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_tipo(id, nombre, descripcion, usario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO proyecto_usuario(proyectoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO ptipo_propiedad(proyecto_tipoid, proyecto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO riesgo(id, nombre, descripcion, riesgo_tipoid, impacto, probabilidad, impacto_monto, impacto_tiempo, gatillo, consecuencia, solucion, riesgos_segundarios, ejecutado, fecha_ejecucion, resultado, observaciones, colaboradorid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO riesgo_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO riesgo_propiedad_valor(riesgoid, riesgo_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO riesgo_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO rol(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO rol_permiso(rolid, permisoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO rol_unidad_ejecutora(id, nombre, estado, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, rol_predeterminado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO rol_usuario_proyecto(rol, proyecto, usuario) VALUES (?, ?, ?);
INSERT INTO rtipo_propiedad(riesgo_tipoid, riesgo_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);
INSERT INTO sctipo_propiedad(subcomponente_tipoid, subcomponente_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO subcomponente(id, nombre, descripcion, componenteid, subcomponente_tipoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, ueunidad_ejecutora, snip, programa, subprograma, proyecto, actividad, obra, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, entidad, ejercicio, fecha_inicio_real, fecha_fin_real, inversion_nueva) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subcomponente_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, dato_tipoid, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subcomponente_propiedad_valor(subcomponenteid, subcomponente_propiedadid, valor_string, valor_entero, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subcomponente_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subcomponente_usuario(subcomponenteid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO subprodtipo_propiedad(subproducto_tipoid, subproducto_propiedadid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO subproducto(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, snip, programa, subprograma, proyecto, actividad, obra, productoid, subproducto_tipoid, ueunidad_ejecutora, latitud, longitud, costo, acumulacion_costoid, renglon, ubicacion_geografica, fecha_inicio, fecha_fin, duracion, duracion_dimension, orden, treePath, nivel, ejercicio, entidad, fecha_inicio_real, fecha_fin_real, inversion_nueva) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subproducto_propiedad(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, dato_tipoid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subproducto_propiedad_valor(subproductoid, subproducto_propiedadid, valor_entero, valor_string, valor_decimal, valor_tiempo, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subproducto_tipo(id, nombre, descripcion, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO subproducto_usuario(subproductoid, usuario, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO tipo_adquisicion(id, cooperantecodigo, cooperanteejercicio, nombre, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, convenio_cdirecta) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO tipo_moneda(id, nombre, simbolo) VALUES (?, ?, ?);
INSERT INTO unidad_ejecutora(unidad_ejecutora, nombre, entidadentidad, ejercicio) VALUES (?, ?, ?, ?);
INSERT INTO unidad_medida(id, nombre, descripcion, usuario_creo, usuario_actualizacion, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO usuario(usuario, password, salt, email, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado, sistema_usuario) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO usuario_log(usuario, fecha) VALUES (?, ?);
INSERT INTO usuario_permiso(usuariousuario, permisoid, usuario_creo, usuario_actualizo, fecha_creacion, fecha_actualizacion, estado) VALUES (?, ?, ?, ?, ?, ?, ?);

/* ------- Updates --------*/

UPDATE actividad SET nombre = ?, descripcion = ?, fecha_inicio = ?, fecha_fin = ?, porcentaje_avance = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, actividad_tipoid = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, objeto_id = ?, objeto_tipo = ?, duracion = ?, duracion_dimension = ?, pred_objeto_id = ?, pred_objeto_tipo = ?, latitud = ?, longitud = ?, costo = ?, acumulacion_costo = ?, renglon = ?, ubicacion_geografica = ?, orden = ?, treePath = ?, nivel = ?, proyecto_base = ?, componente_base = ?, producto_base = ?, fecha_inicio_real = ?, fecha_fin_real = ?, inversion_nueva = ? WHERE id = ?;
UPDATE actividad_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, dato_tipoid = ? WHERE id = ?;
UPDATE actividad_propiedad_valor SET valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE actividadid = ? AND actividad_propiedadid = ?;
UPDATE actividad_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE actividad_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE actividadid = ? AND usuario = ?;
UPDATE acumulacion_costo SET nombre = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE asignacion_raci SET matriz_raciid = ?, colaboradorid = ?, rol_raci = ?, objeto_id = ?, objeto_tipo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE atipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE actividad_tipoid = ? AND actividad_propiedadid = ?;
UPDATE autorizacion_tipo SET nombre = ?, descripcion = ? WHERE id = ?;
UPDATE categoria_adquisicion SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE colaborador SET pnombre = ?, snombre = ?, papellido = ?, sapellido = ?, cui = ?, ueunidad_ejecutora = ?, usuariousuario = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, ejercicio = ?, entidad = ? WHERE id = ?;
UPDATE componente SET nombre = ?, descripcion = ?, proyectoid = ?, componente_tipoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, ueunidad_ejecutora = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, latitud = ?, longitud = ?, costo = ?, acumulacion_costoid = ?, renglon = ?, ubicacion_geografica = ?, fecha_inicio = ?, fecha_fin = ?, duracion = ?, duracion_dimension = ?, orden = ?, treepath = ?, nivel = ?, ejercicio = ?, entidad = ?, es_de_sigade = ?, fuente_prestamo = ?, fuente_donacion = ?, fuente_nacional = ?, componente_sigadeid = ?, fecha_inicio_real = ?, fecha_fin_real = ?, inversion_nueva = ? WHERE id = ?;
UPDATE componente_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, dato_tipoid = ?, estado = ? WHERE id = ?;
UPDATE componente_propiedad_valor SET valor_string = ?, valor_entero = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE componenteid = ? AND componente_propiedadid = ?;
UPDATE componente_sigade SET nombre = ?, codigo_presupuestario = ?, numero_componente = ?, monto_componente = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE componente_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE componente_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE componenteid = ? AND usuario = ?;
UPDATE cooperante SET siglas = ?, nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE codigo = ? AND ejercicio = ?;
UPDATE ctipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE componente_tipoid = ? AND componente_propiedadid = ?;
UPDATE dato_tipo SET nombre = ?, descripcion = ? WHERE id = ?;
UPDATE desembolso SET fecha = ?, estado = ?, monto = ?, tipo_cambio = ?, monto_moneda_origen = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, proyectoid = ?, desembolso_tipoid = ?, tipo_monedaid = ? WHERE id = ?;
UPDATE desembolso_tipo SET nombre = ?, descripcion = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE id = ?;
UPDATE documento SET nombre = ?, extension = ?, id_tipo_objeto = ?, id_objeto = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE ejecucion_estado SET nombre = ?, descripcion = ? WHERE id = ?;
UPDATE entidad SET nombre = ?, abreviatura = ?, ejercicio = ? WHERE entidad = ?;
UPDATE estado SET id = ?, nombre = ?, valor = ? WHERE ;
UPDATE estado_tabla SET valores = ? WHERE usuario = ? AND tabla = ?;
UPDATE etiqueta SET nombre = ?, descripcion = ?, proyecto = ?, color_principal = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE formulario SET codigo = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, formulario_tipoid = ? WHERE id = ?;
UPDATE formulario_item SET texto = ?, formularioid = ?, orden = ?, usuario_creo = ?, usuario_actualizacion = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, formulario_item_tipoid = ? WHERE id = ?;
UPDATE formulario_item_opcion SET formulario_itemid = ?, etiqueta = ?, valor_entero = ?, valor_string = ?, valor_tiempo = ?, valor_decimal = ?, estado = ?, usuario_creo = ?, usuario_actualizacion = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE id = ?;
UPDATE formulario_item_tipo SET nombre = ?, descripcion = ?, estado = ?, usuario_creo = ?, fecha_creacion = ?, usuario_actualizacion = ?, fecha_actualizacion = ?, dato_tipoid = ? WHERE id = ?;
UPDATE formulario_item_valor SET valor_entero = ?, valor_string = ?, valor_tiempo = ?, valor_decimal = ?, proyectoid = ?, componenteid = ?, productoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE formulario_itemid = ? AND objeto_formularioformularioid = ? AND objeto_formularioobjeto_tipoid = ? AND objeto_formularioobjeto_id = ?;
UPDATE formulario_tipo SET nombre = ?, descripcion = ?, usario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE hito SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, fecha = ?, proyectoid = ?, hito_tipoid = ? WHERE id = ?;
UPDATE hito_resultado SET valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, comentario = ?, hitoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE hito_tipo SET nombre = ?, descripcion = ?, estado = ?, dato_tipoid = ?, usuario_creo = ?, usuario_actualizacion = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE id = ?;
UPDATE interes_tipo SET nombre = ?, descripcion = ? WHERE id = ?;
UPDATE linea_base SET nombre = ?, proyectoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, tipo_linea_base = ?, sobreescribir = ? WHERE id = ?;
UPDATE matriz_raci SET proyectoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE meta SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, meta_unidad_medidaid = ?, dato_tipoid = ?, objeto_id = ?, objeto_tipo = ?, meta_final_entero = ?, meta_final_string = ?, meta_final_decimal = ?, meta_final_fecha = ? WHERE id = ?;
UPDATE meta_avance SET metaid = ?, fecha = ?, usuario = ?, valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, estado = ?, fecha_ingreso = ? WHERE ;
UPDATE meta_planificado SET enero_entero = ?, enero_string = ?, enero_decimal = ?, enero_tiempo = ?, febrero_entero = ?, febrero_string = ?, febrero_decimal = ?, febrero_tiempo = ?, marzo_entero = ?, marzo_string = ?, marzo_decimal = ?, marzo_tiempo = ?, abril_entero = ?, abril_string = ?, abril_decimal = ?, abril_tiempo = ?, mayo_entero = ?, mayo_string = ?, mayo_decimal = ?, mayo_tiempo = ?, junio_entero = ?, junio_string = ?, junio_decimal = ?, junio_tiempo = ?, julio_entero = ?, julio_string = ?, julio_decimal = ?, julio_tiempo = ?, agosto_entero = ?, agosto_string = ?, agosto_decimal = ?, agosto_tiempo = ?, septiembre_entero = ?, septiembre_string = ?, septiembre_decimal = ?, septiembre_tiempo = ?, octubre_entero = ?, octubre_string = ?, octubre_decimal = ?, octubre_tiempo = ?, noviembre_entero = ?, noviembre_string = ?, noviembre_decimal = ?, noviembre_tiempo = ?, diciembre_entero = ?, diciembre_string = ?, diciembre_decimal = ?, diciembre_tiempo = ?, estado = ?, usuario = ?, fecha_ingreso = ? WHERE metaid = ? AND ejercicio = ?;
UPDATE meta_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE meta_unidad_medida SET nombre = ?, descripcion = ?, simbolo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE meta_valor SET usuario = ?, valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ? WHERE metaid = ? AND fecha = ?;
UPDATE objeto_formulario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE formularioid = ? AND objeto_tipo = ? AND objeto_id = ?;
UPDATE objeto_riesgo SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE riesgoid = ? AND objeto_id = ? AND objeto_tipo = ?;
UPDATE pago_planificado SET fecha_pago = ?, pago = ?, objeto_id = ?, objeto_tipo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE pep_detalle SET observaciones = ?, alertivos = ?, elaborado = ?, aprobado = ?, autoridad = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE proyectoid = ?;
UPDATE permiso SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE plan_adquisicion SET tipo_adquisicion = ?, categoria_adquisicion = ?, unidad_medida = ?, cantidad = ?, total = ?, precio_unitario = ?, preparacion_doc_planificado = ?, preparacion_doc_real = ?, lanzamiento_evento_planificado = ?, lanzamiento_evento_real = ?, recepcion_ofertas_planificado = ?, recepcion_ofertas_real = ?, adjudicacion_planificado = ?, adjudicacion_real = ?, firma_contrato_planificado = ?, firma_contrato_real = ?, objeto_id = ?, objeto_tipo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, bloqueado = ?, numero_contrato = ?, monto_contrato = ?, nog = ?, tipo_revision = ? WHERE id = ?;
UPDATE plan_adquisicion_pago SET plan_adquisicionid = ?, fecha_pago = ?, pago = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE prestamo SET fecha_corte = ?, codigo_presupuestario = ?, numero_prestamo = ?, destino = ?, sector_economico = ?, ueunidad_ejecutora = ?, fecha_firma = ?, autorizacion_tipoid = ?, numero_autorizacion = ?, fecha_autorizacion = ?, anios_plazo = ?, anios_gracia = ?, fecha_fin_ejecucion = ?, perido_ejecucion = ?, interes_tipoid = ?, porcentaje_interes = ?, porcentaje_comision_compra = ?, tipo_monedaid = ?, monto_contratado = ?, amortizado = ?, por_amortizar = ?, principal_anio = ?, intereses_anio = ?, comision_compromiso_anio = ?, otros_gastos = ?, principal_acumulado = ?, intereses_acumulados = ?, comision_compromiso_acumulado = ?, otros_cargos_acumulados = ?, presupuesto_asignado_func = ?, presupuesto_asignado_inv = ?, presupuesto_modificado_func = ?, presupuesto_modificado_inv = ?, presupuesto_vigente_func = ?, presupuesto_vigente_inv = ?, presupuesto_devengado_func = ?, presupuesto_devengado_inv = ?, presupuesto_pagado_func = ?, presupuesto_pagado_inv = ?, saldo_cuentas = ?, desembolsado_real = ?, ejecucion_estadoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, proyecto_programa = ?, fecha_decreto = ?, fecha_suscripcion = ?, fecha_elegibilidad_ue = ?, fecha_cierre_origianl_ue = ?, fecha_cierre_actual_ue = ?, meses_prorroga_ue = ?, plazo_ejecucion_ue = ?, monto_asignado_ue = ?, desembolso_a_fecha_ue = ?, monto_por_desembolsar_ue = ?, fecha_vigencia = ?, monto_contratado_usd = ?, monto_contratado_qtz = ?, desembolso_a_fecha_usd = ?, monto_por_desembolsar_usd = ?, monto_asignado_ue_usd = ?, monto_asignado_ue_qtz = ?, desembolso_a_fecha_ue_usd = ?, monto_por_desembolsar_ue_usd = ?, entidad = ?, ejercicio = ?, objetivo = ?, objetivo_especifico = ?, porcentaje_avance = ?, cooperantecodigo = ?, cooperanteejercicio = ? WHERE id = ?;
UPDATE prestamo_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE prestamo_tipo_prestamo SET prestamoId = ?, tipoPrestamoId = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE ;
UPDATE prestamo_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE prestamoid = ? AND usuario = ?;
UPDATE prodtipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE producto_tipoid = ? AND producto_propiedadid = ?;
UPDATE producto SET nombre = ?, descripcion = ?, componenteid = ?, subcomponenteid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, producto_tipoid = ?, estado = ?, ueunidad_ejecutora = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, latitud = ?, longitud = ?, peso = ?, costo = ?, acumulacion_costoid = ?, renglon = ?, ubicacion_geografica = ?, fecha_inicio = ?, fecha_fin = ?, duracion = ?, duracion_dimension = ?, orden = ?, treePath = ?, nivel = ?, ejercicio = ?, entidad = ?, fecha_inicio_real = ?, fecha_fin_real = ?, inversion_nueva = ? WHERE id = ?;
UPDATE producto_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, dato_tipoid = ?, estado = ? WHERE id = ?;
UPDATE producto_propiedad_valor SET valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE producto_propiedadid = ? AND productoid = ?;
UPDATE producto_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE producto_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE productoid = ? AND usuario = ?;
UPDATE proyecto SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, proyecto_tipoid = ?, ueunidad_ejecutora = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, latitud = ?, longitud = ?, objetivo = ?, director_proyecto = ?, enunciado_alcance = ?, costo = ?, acumulacion_costoid = ?, objetivo_especifico = ?, vision_general = ?, renglon = ?, ubicacion_geografica = ?, fecha_inicio = ?, fecha_fin = ?, duracion = ?, duracion_dimension = ?, orden = ?, treePath = ?, nivel = ?, ejercicio = ?, entidad = ?, ejecucion_fisica_real = ?, proyecto_clase = ?, project_cargado = ?, prestamoid = ?, observaciones = ?, coordinador = ?, fecha_elegibilidad = ?, fecha_inicio_real = ?, fecha_fin_real = ?, congelado = ?, fecha_cierre = ? WHERE id = ?;
UPDATE proyecto_impacto SET proyectoid = ?, entidadentidad = ?, impacto = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, ejercicio = ? WHERE id = ?;
UPDATE proyecto_miembro SET estado = ?, fecha_creacion = ?, fecha_actualizacion = ?, usuario_creo = ?, usuario_actualizo = ? WHERE proyectoid = ? AND colaboradorid = ?;
UPDATE proyecto_propiedad SET nombre = ?, descripcion = ?, dato_tipoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE proyecto_propiedad_valor SET valor_string = ?, valor_entero = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE proyectoid = ? AND proyecto_propiedadid = ?;
UPDATE proyecto_rol_colaborador SET colaboradorid = ?, proyectoid = ?, rol_unidad_ejecutoraid = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE id = ?;
UPDATE proyecto_tipo SET nombre = ?, descripcion = ?, usario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE proyecto_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE proyectoid = ? AND usuario = ?;
UPDATE ptipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE proyecto_tipoid = ? AND proyecto_propiedadid = ?;
UPDATE riesgo SET nombre = ?, descripcion = ?, riesgo_tipoid = ?, impacto = ?, probabilidad = ?, impacto_monto = ?, impacto_tiempo = ?, gatillo = ?, consecuencia = ?, solucion = ?, riesgos_segundarios = ?, ejecutado = ?, fecha_ejecucion = ?, resultado = ?, observaciones = ?, colaboradorid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE riesgo_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, dato_tipoid = ? WHERE id = ?;
UPDATE riesgo_propiedad_valor SET valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE riesgoid = ? AND riesgo_propiedadid = ?;
UPDATE riesgo_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE rol SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE rol_permiso SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE rolid = ? AND permisoid = ?;
UPDATE rol_unidad_ejecutora SET nombre = ?, estado = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, rol_predeterminado = ? WHERE id = ?;
UPDATE rol_usuario_proyecto SET  WHERE rol = ? AND proyecto = ? AND usuario = ?;
UPDATE rtipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE riesgo_tipoid = ? AND riesgo_propiedadid = ?;
UPDATE sctipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE subcomponente_tipoid = ? AND subcomponente_propiedadid = ?;
UPDATE subcomponente SET nombre = ?, descripcion = ?, componenteid = ?, subcomponente_tipoid = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, ueunidad_ejecutora = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, latitud = ?, longitud = ?, costo = ?, acumulacion_costoid = ?, renglon = ?, ubicacion_geografica = ?, fecha_inicio = ?, fecha_fin = ?, duracion = ?, duracion_dimension = ?, orden = ?, treePath = ?, nivel = ?, entidad = ?, ejercicio = ?, fecha_inicio_real = ?, fecha_fin_real = ?, inversion_nueva = ? WHERE id = ?;
UPDATE subcomponente_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, dato_tipoid = ?, estado = ? WHERE id = ?;
UPDATE subcomponente_propiedad_valor SET valor_string = ?, valor_entero = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE subcomponenteid = ? AND subcomponente_propiedadid = ?;
UPDATE subcomponente_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE subcomponente_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE subcomponenteid = ? AND usuario = ?;
UPDATE subprodtipo_propiedad SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE subproducto_tipoid = ? AND subproducto_propiedadid = ?;
UPDATE subproducto SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, snip = ?, programa = ?, subprograma = ?, proyecto = ?, actividad = ?, obra = ?, productoid = ?, subproducto_tipoid = ?, ueunidad_ejecutora = ?, latitud = ?, longitud = ?, costo = ?, acumulacion_costoid = ?, renglon = ?, ubicacion_geografica = ?, fecha_inicio = ?, fecha_fin = ?, duracion = ?, duracion_dimension = ?, orden = ?, treePath = ?, nivel = ?, ejercicio = ?, entidad = ?, fecha_inicio_real = ?, fecha_fin_real = ?, inversion_nueva = ? WHERE id = ?;
UPDATE subproducto_propiedad SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, dato_tipoid = ? WHERE id = ?;
UPDATE subproducto_propiedad_valor SET valor_entero = ?, valor_string = ?, valor_decimal = ?, valor_tiempo = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE subproductoid = ? AND subproducto_propiedadid = ?;
UPDATE subproducto_tipo SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE subproducto_usuario SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ? WHERE subproductoid = ? AND usuario = ?;
UPDATE tipo_adquisicion SET cooperantecodigo = ?, cooperanteejercicio = ?, nombre = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, convenio_cdirecta = ? WHERE id = ?;
UPDATE tipo_moneda SET nombre = ?, simbolo = ? WHERE id = ?;
UPDATE unidad_ejecutora SET nombre = ? WHERE unidad_ejecutora = ? AND entidadentidad = ? AND ejercicio = ?;
UPDATE unidad_medida SET nombre = ?, descripcion = ?, usuario_creo = ?, usuario_actualizacion = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE id = ?;
UPDATE usuario SET password = ?, salt = ?, email = ?, usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ?, sistema_usuario = ? WHERE usuario = ?;
UPDATE usuario_log SET usuario = ?, fecha = ? WHERE ;
UPDATE usuario_permiso SET usuario_creo = ?, usuario_actualizo = ?, fecha_creacion = ?, fecha_actualizacion = ?, estado = ? WHERE usuariousuario = ? AND permisoid = ?;

/* ------- Deletes --------*/

DELETE FROM actividad WHERE id = ?;
DELETE FROM actividad_propiedad WHERE id = ?;
DELETE FROM actividad_propiedad_valor WHERE actividadid = ? AND actividad_propiedadid = ?;
DELETE FROM actividad_tipo WHERE id = ?;
DELETE FROM actividad_usuario WHERE actividadid = ? AND usuario = ?;
DELETE FROM acumulacion_costo WHERE id = ?;
DELETE FROM asignacion_raci WHERE id = ?;
DELETE FROM atipo_propiedad WHERE actividad_tipoid = ? AND actividad_propiedadid = ?;
DELETE FROM autorizacion_tipo WHERE id = ?;
DELETE FROM categoria_adquisicion WHERE id = ?;
DELETE FROM colaborador WHERE id = ?;
DELETE FROM componente WHERE id = ?;
DELETE FROM componente_propiedad WHERE id = ?;
DELETE FROM componente_propiedad_valor WHERE componenteid = ? AND componente_propiedadid = ?;
DELETE FROM componente_sigade WHERE id = ?;
DELETE FROM componente_tipo WHERE id = ?;
DELETE FROM componente_usuario WHERE componenteid = ? AND usuario = ?;
DELETE FROM cooperante WHERE codigo = ? AND ejercicio = ?;
DELETE FROM ctipo_propiedad WHERE componente_tipoid = ? AND componente_propiedadid = ?;
DELETE FROM dato_tipo WHERE id = ?;
DELETE FROM desembolso WHERE id = ?;
DELETE FROM desembolso_tipo WHERE id = ?;
DELETE FROM documento WHERE id = ?;
DELETE FROM ejecucion_estado WHERE id = ?;
DELETE FROM entidad WHERE entidad = ?;
DELETE FROM estado WHERE ;
DELETE FROM estado_tabla WHERE usuario = ? AND tabla = ?;
DELETE FROM etiqueta WHERE id = ?;
DELETE FROM formulario WHERE id = ?;
DELETE FROM formulario_item WHERE id = ?;
DELETE FROM formulario_item_opcion WHERE id = ?;
DELETE FROM formulario_item_tipo WHERE id = ?;
DELETE FROM formulario_item_valor WHERE formulario_itemid = ? AND objeto_formularioformularioid = ? AND objeto_formularioobjeto_tipoid = ? AND objeto_formularioobjeto_id = ?;
DELETE FROM formulario_tipo WHERE id = ?;
DELETE FROM hito WHERE id = ?;
DELETE FROM hito_resultado WHERE id = ?;
DELETE FROM hito_tipo WHERE id = ?;
DELETE FROM interes_tipo WHERE id = ?;
DELETE FROM linea_base WHERE id = ?;
DELETE FROM matriz_raci WHERE id = ?;
DELETE FROM meta WHERE id = ?;
DELETE FROM meta_avance WHERE ;
DELETE FROM meta_planificado WHERE metaid = ? AND ejercicio = ?;
DELETE FROM meta_tipo WHERE id = ?;
DELETE FROM meta_unidad_medida WHERE id = ?;
DELETE FROM meta_valor WHERE metaid = ? AND fecha = ?;
DELETE FROM objeto_formulario WHERE formularioid = ? AND objeto_tipo = ? AND objeto_id = ?;
DELETE FROM objeto_riesgo WHERE riesgoid = ? AND objeto_id = ? AND objeto_tipo = ?;
DELETE FROM pago_planificado WHERE id = ?;
DELETE FROM pep_detalle WHERE proyectoid = ?;
DELETE FROM permiso WHERE id = ?;
DELETE FROM plan_adquisicion WHERE id = ?;
DELETE FROM plan_adquisicion_pago WHERE id = ?;
DELETE FROM prestamo WHERE id = ?;
DELETE FROM prestamo_tipo WHERE id = ?;
DELETE FROM prestamo_tipo_prestamo WHERE ;
DELETE FROM prestamo_usuario WHERE prestamoid = ? AND usuario = ?;
DELETE FROM prodtipo_propiedad WHERE producto_tipoid = ? AND producto_propiedadid = ?;
DELETE FROM producto WHERE id = ?;
DELETE FROM producto_propiedad WHERE id = ?;
DELETE FROM producto_propiedad_valor WHERE producto_propiedadid = ? AND productoid = ?;
DELETE FROM producto_tipo WHERE id = ?;
DELETE FROM producto_usuario WHERE productoid = ? AND usuario = ?;
DELETE FROM proyecto WHERE id = ?;
DELETE FROM proyecto_impacto WHERE id = ?;
DELETE FROM proyecto_miembro WHERE proyectoid = ? AND colaboradorid = ?;
DELETE FROM proyecto_propiedad WHERE id = ?;
DELETE FROM proyecto_propiedad_valor WHERE proyectoid = ? AND proyecto_propiedadid = ?;
DELETE FROM proyecto_rol_colaborador WHERE id = ?;
DELETE FROM proyecto_tipo WHERE id = ?;
DELETE FROM proyecto_usuario WHERE proyectoid = ? AND usuario = ?;
DELETE FROM ptipo_propiedad WHERE proyecto_tipoid = ? AND proyecto_propiedadid = ?;
DELETE FROM riesgo WHERE id = ?;
DELETE FROM riesgo_propiedad WHERE id = ?;
DELETE FROM riesgo_propiedad_valor WHERE riesgoid = ? AND riesgo_propiedadid = ?;
DELETE FROM riesgo_tipo WHERE id = ?;
DELETE FROM rol WHERE id = ?;
DELETE FROM rol_permiso WHERE rolid = ? AND permisoid = ?;
DELETE FROM rol_unidad_ejecutora WHERE id = ?;
DELETE FROM rol_usuario_proyecto WHERE rol = ? AND proyecto = ? AND usuario = ?;
DELETE FROM rtipo_propiedad WHERE riesgo_tipoid = ? AND riesgo_propiedadid = ?;
DELETE FROM sctipo_propiedad WHERE subcomponente_tipoid = ? AND subcomponente_propiedadid = ?;
DELETE FROM subcomponente WHERE id = ?;
DELETE FROM subcomponente_propiedad WHERE id = ?;
DELETE FROM subcomponente_propiedad_valor WHERE subcomponenteid = ? AND subcomponente_propiedadid = ?;
DELETE FROM subcomponente_tipo WHERE id = ?;
DELETE FROM subcomponente_usuario WHERE subcomponenteid = ? AND usuario = ?;
DELETE FROM subprodtipo_propiedad WHERE subproducto_tipoid = ? AND subproducto_propiedadid = ?;
DELETE FROM subproducto WHERE id = ?;
DELETE FROM subproducto_propiedad WHERE id = ?;
DELETE FROM subproducto_propiedad_valor WHERE subproductoid = ? AND subproducto_propiedadid = ?;
DELETE FROM subproducto_tipo WHERE id = ?;
DELETE FROM subproducto_usuario WHERE subproductoid = ? AND usuario = ?;
DELETE FROM tipo_adquisicion WHERE id = ?;
DELETE FROM tipo_moneda WHERE id = ?;
DELETE FROM unidad_ejecutora WHERE unidad_ejecutora = ? AND entidadentidad = ? AND ejercicio = ?;
DELETE FROM unidad_medida WHERE id = ?;
DELETE FROM usuario WHERE usuario = ?;
DELETE FROM usuario_log WHERE ;
DELETE FROM usuario_permiso WHERE usuariousuario = ? AND permisoid = ?;
