DROP SEQUENCE seq_actividad;
DROP SEQUENCE seq_actividad_propiedad;
DROP SEQUENCE seq_actividad_tipo;
DROP SEQUENCE seq_acumulacion_costo;
DROP SEQUENCE seq_asignacion_raci;
DROP SEQUENCE seq_autorizacion_tipo;
DROP SEQUENCE seq_categoria_adquisicion;
DROP SEQUENCE seq_colaborador;
DROP SEQUENCE seq_componente;
DROP SEQUENCE seq_componente_propiedad;
DROP SEQUENCE seq_componente_sigade;
DROP SEQUENCE seq_componente_tipo;
DROP SEQUENCE seq_dato_tipo;
DROP SEQUENCE seq_desembolso;
DROP SEQUENCE seq_desembolso_tipo;
DROP SEQUENCE seq_documento;
DROP SEQUENCE seq_ejecucion_estado;
DROP SEQUENCE seq_entidad;
DROP SEQUENCE seq_etiqueta;
DROP SEQUENCE seq_formulario;
DROP SEQUENCE seq_formulario_item;
DROP SEQUENCE seq_formulario_item_opcion;
DROP SEQUENCE seq_formulario_item_tipo;
DROP SEQUENCE seq_formulario_tipo;
DROP SEQUENCE seq_hito;
DROP SEQUENCE seq_hito_resultado;
DROP SEQUENCE seq_hito_tipo;
DROP SEQUENCE seq_interes_tipo;
DROP SEQUENCE seq_linea_base;
DROP SEQUENCE seq_matriz_raci;
DROP SEQUENCE seq_meta;
DROP SEQUENCE seq_meta_tipo;
DROP SEQUENCE seq_meta_unidad_medida;
DROP SEQUENCE seq_pago_planificado;
DROP SEQUENCE seq_permiso;
DROP SEQUENCE seq_plan_adquisicion;
DROP SEQUENCE seq_plan_adquisicion_pago;
DROP SEQUENCE seq_prestamo;
DROP SEQUENCE seq_prestamo_tipo;
DROP SEQUENCE seq_producto;
DROP SEQUENCE seq_producto_propiedad;
DROP SEQUENCE seq_producto_tipo;
DROP SEQUENCE seq_proyecto;
DROP SEQUENCE seq_proyecto_impacto;
DROP SEQUENCE seq_proyecto_propiedad;
DROP SEQUENCE seq_proyecto_rol_colaborador;
DROP SEQUENCE seq_proyecto_tipo;
DROP SEQUENCE seq_riesgo;
DROP SEQUENCE seq_riesgo_propiedad;
DROP SEQUENCE seq_riesgo_tipo;
DROP SEQUENCE seq_rol;
DROP SEQUENCE seq_rol_unidad_ejecutora;
DROP SEQUENCE seq_subcomponente;
DROP SEQUENCE seq_subcomponente_propiedad;
DROP SEQUENCE seq_subcomponente_tipo;
DROP SEQUENCE seq_subproducto;
DROP SEQUENCE seq_subproducto_propiedad;
DROP SEQUENCE seq_subproducto_tipo;
DROP SEQUENCE seq_tipo_adquisicion;
DROP SEQUENCE seq_tipo_moneda;
DROP SEQUENCE seq_unidad_medida;
DROP TABLE actividad CASCADE CONSTRAINTS;
DROP TABLE actividad_propiedad CASCADE CONSTRAINTS;
DROP TABLE actividad_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE actividad_tipo CASCADE CONSTRAINTS;
DROP TABLE actividad_usuario CASCADE CONSTRAINTS;
DROP TABLE acumulacion_costo CASCADE CONSTRAINTS;
DROP TABLE asignacion_raci CASCADE CONSTRAINTS;
DROP TABLE atipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE autorizacion_tipo CASCADE CONSTRAINTS;
DROP TABLE categoria_adquisicion CASCADE CONSTRAINTS;
DROP TABLE colaborador CASCADE CONSTRAINTS;
DROP TABLE componente CASCADE CONSTRAINTS;
DROP TABLE componente_propiedad CASCADE CONSTRAINTS;
DROP TABLE componente_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE componente_sigade CASCADE CONSTRAINTS;
DROP TABLE componente_tipo CASCADE CONSTRAINTS;
DROP TABLE componente_usuario CASCADE CONSTRAINTS;
DROP TABLE cooperante CASCADE CONSTRAINTS;
DROP TABLE ctipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE dato_tipo CASCADE CONSTRAINTS;
DROP TABLE desembolso CASCADE CONSTRAINTS;
DROP TABLE desembolso_tipo CASCADE CONSTRAINTS;
DROP TABLE documento CASCADE CONSTRAINTS;
DROP TABLE ejecucion_estado CASCADE CONSTRAINTS;
DROP TABLE entidad CASCADE CONSTRAINTS;
DROP TABLE estado CASCADE CONSTRAINTS;
DROP TABLE estado_tabla CASCADE CONSTRAINTS;
DROP TABLE etiqueta CASCADE CONSTRAINTS;
DROP TABLE formulario CASCADE CONSTRAINTS;
DROP TABLE formulario_item CASCADE CONSTRAINTS;
DROP TABLE formulario_item_opcion CASCADE CONSTRAINTS;
DROP TABLE formulario_item_tipo CASCADE CONSTRAINTS;
DROP TABLE formulario_item_valor CASCADE CONSTRAINTS;
DROP TABLE formulario_tipo CASCADE CONSTRAINTS;
DROP TABLE hito CASCADE CONSTRAINTS;
DROP TABLE hito_resultado CASCADE CONSTRAINTS;
DROP TABLE hito_tipo CASCADE CONSTRAINTS;
DROP TABLE interes_tipo CASCADE CONSTRAINTS;
DROP TABLE linea_base CASCADE CONSTRAINTS;
DROP TABLE matriz_raci CASCADE CONSTRAINTS;
DROP TABLE meta CASCADE CONSTRAINTS;
DROP TABLE meta_avance CASCADE CONSTRAINTS;
DROP TABLE meta_planificado CASCADE CONSTRAINTS;
DROP TABLE meta_tipo CASCADE CONSTRAINTS;
DROP TABLE meta_unidad_medida CASCADE CONSTRAINTS;
DROP TABLE meta_valor CASCADE CONSTRAINTS;
DROP TABLE objeto_formulario CASCADE CONSTRAINTS;
DROP TABLE objeto_riesgo CASCADE CONSTRAINTS;
DROP TABLE pago_planificado CASCADE CONSTRAINTS;
DROP TABLE pep_detalle CASCADE CONSTRAINTS;
DROP TABLE permiso CASCADE CONSTRAINTS;
DROP TABLE plan_adquisicion CASCADE CONSTRAINTS;
DROP TABLE plan_adquisicion_pago CASCADE CONSTRAINTS;
DROP TABLE prestamo CASCADE CONSTRAINTS;
DROP TABLE prestamo_tipo CASCADE CONSTRAINTS;
DROP TABLE prestamo_tipo_prestamo CASCADE CONSTRAINTS;
DROP TABLE prestamo_usuario CASCADE CONSTRAINTS;
DROP TABLE prodtipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;
DROP TABLE producto_propiedad CASCADE CONSTRAINTS;
DROP TABLE producto_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE producto_tipo CASCADE CONSTRAINTS;
DROP TABLE producto_usuario CASCADE CONSTRAINTS;
DROP TABLE proyecto CASCADE CONSTRAINTS;
DROP TABLE proyecto_impacto CASCADE CONSTRAINTS;
DROP TABLE proyecto_miembro CASCADE CONSTRAINTS;
DROP TABLE proyecto_propiedad CASCADE CONSTRAINTS;
DROP TABLE proyecto_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE proyecto_rol_colaborador CASCADE CONSTRAINTS;
DROP TABLE proyecto_tipo CASCADE CONSTRAINTS;
DROP TABLE proyecto_usuario CASCADE CONSTRAINTS;
DROP TABLE ptipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE riesgo CASCADE CONSTRAINTS;
DROP TABLE riesgo_propiedad CASCADE CONSTRAINTS;
DROP TABLE riesgo_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE riesgo_tipo CASCADE CONSTRAINTS;
DROP TABLE rol CASCADE CONSTRAINTS;
DROP TABLE rol_permiso CASCADE CONSTRAINTS;
DROP TABLE rol_unidad_ejecutora CASCADE CONSTRAINTS;
DROP TABLE rol_usuario_proyecto CASCADE CONSTRAINTS;
DROP TABLE rtipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE sctipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE subcomponente CASCADE CONSTRAINTS;
DROP TABLE subcomponente_propiedad CASCADE CONSTRAINTS;
DROP TABLE subcomponente_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE subcomponente_tipo CASCADE CONSTRAINTS;
DROP TABLE subcomponente_usuario CASCADE CONSTRAINTS;
DROP TABLE subprodtipo_propiedad CASCADE CONSTRAINTS;
DROP TABLE subproducto CASCADE CONSTRAINTS;
DROP TABLE subproducto_propiedad CASCADE CONSTRAINTS;
DROP TABLE subproducto_propiedad_valor CASCADE CONSTRAINTS;
DROP TABLE subproducto_tipo CASCADE CONSTRAINTS;
DROP TABLE subproducto_usuario CASCADE CONSTRAINTS;
DROP TABLE tipo_adquisicion CASCADE CONSTRAINTS;
DROP TABLE tipo_moneda CASCADE CONSTRAINTS;
DROP TABLE unidad_ejecutora CASCADE CONSTRAINTS;
DROP TABLE unidad_medida CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE usuario_log CASCADE CONSTRAINTS;
DROP TABLE usuario_permiso CASCADE CONSTRAINTS;

CREATE SEQUENCE seq_actividad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_actividad_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_actividad_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_acumulacion_costo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_asignacion_raci START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_autorizacion_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_categoria_adquisicion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_colaborador START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_componente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_componente_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_componente_sigade START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_componente_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dato_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_desembolso START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_desembolso_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_documento START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ejecucion_estado START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_entidad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_etiqueta START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formulario START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formulario_item START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formulario_item_opcion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formulario_item_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formulario_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hito START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hito_resultado START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_hito_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_interes_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_linea_base START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_matriz_raci START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_meta START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_meta_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_meta_unidad_medida START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pago_planificado START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_permiso START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_plan_adquisicion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_plan_adquisicion_pago START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_prestamo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_prestamo_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_producto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_producto_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_producto_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto_impacto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto_rol_colaborador START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_proyecto_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_riesgo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_riesgo_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_riesgo_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_rol START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_rol_unidad_ejecutora START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subcomponente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subcomponente_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subcomponente_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subproducto START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subproducto_propiedad START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subproducto_tipo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipo_adquisicion START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipo_moneda START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_unidad_medida START WITH 1 INCREMENT BY 1;
CREATE TABLE actividad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(1000), fecha_inicio timestamp(0) NOT NULL, fecha_fin timestamp(0) NOT NULL, porcentaje_avance number(3) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, actividad_tipoid number(10) NOT NULL, snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), objeto_id number(11) NOT NULL, objeto_tipo number(2) NOT NULL, duracion number(10) NOT NULL, duracion_dimension varchar2(1) NOT NULL, pred_objeto_id number(11), pred_objeto_tipo number(2), latitud varchar2(30), longitud varchar2(30), costo number(15, 2), acumulacion_costo number(11) NOT NULL, renglon number(4), ubicacion_geografica number(4), orden number(10), treePath varchar2(1000), nivel number(4), proyecto_base number(11), componente_base number(10), producto_base number(10), fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), inversion_nueva number(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE actividad_propiedad (id number(10) NOT NULL, nombre varchar2(200) NOT NULL, descripcion varchar2(1000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, dato_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE actividad_propiedad_valor (actividadid number(10) NOT NULL, actividad_propiedadid number(10) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), estado number(2), PRIMARY KEY (actividadid, actividad_propiedadid));
CREATE TABLE actividad_tipo (id number(10) NOT NULL, nombre varchar2(200) NOT NULL, descripcion varchar2(1000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE actividad_usuario (actividadid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (actividadid, usuario));
CREATE TABLE acumulacion_costo (id number(11) NOT NULL, nombre varchar2(45) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE asignacion_raci (id number(11) NOT NULL, matriz_raciid number(11) NOT NULL, colaboradorid number(10) NOT NULL, rol_raci varchar2(1) NOT NULL, objeto_id number(11) NOT NULL, objeto_tipo number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE atipo_propiedad (actividad_tipoid number(10) NOT NULL, actividad_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (actividad_tipoid, actividad_propiedadid));
CREATE TABLE autorizacion_tipo (id number(10) NOT NULL, nombre varchar2(100) NOT NULL, descripcion varchar2(1000), PRIMARY KEY (id));
CREATE TABLE categoria_adquisicion (id number(11) NOT NULL, nombre varchar2(45) NOT NULL, descripcion varchar2(100), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE colaborador (id number(10) NOT NULL, pnombre varchar2(255) NOT NULL, snombre varchar2(255), papellido varchar2(255) NOT NULL, sapellido varchar2(255), cui number(15) NOT NULL, ueunidad_ejecutora number(10) NOT NULL, usuariousuario varchar2(30) NOT NULL, estado number(1) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), ejercicio number(4) NOT NULL, entidad number(10), PRIMARY KEY (id));
CREATE TABLE componente (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), proyectoid number(10) NOT NULL, componente_tipoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, ueunidad_ejecutora number(10) NOT NULL, snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), latitud varchar2(30), longitud varchar2(30), costo number(15, 2), acumulacion_costoid number(11), renglon number(4), ubicacion_geografica number(4), fecha_inicio timestamp(0), fecha_fin timestamp(0), duracion number(10) NOT NULL, duracion_dimension varchar2(1), orden number(10), treepath varchar2(1000), nivel number(4), ejercicio number(4) NOT NULL, entidad number(10), es_de_sigade number(1), fuente_prestamo number(15, 2), fuente_donacion number(15, 2), fuente_nacional number(15, 2), componente_sigadeid number(10) NOT NULL, fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), inversion_nueva number(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE componente_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), dato_tipoid number(10) NOT NULL, estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE componente_propiedad_valor (componenteid number(10) NOT NULL, componente_propiedadid number(10) NOT NULL, valor_string varchar2(4000), valor_entero number(10), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (componenteid, componente_propiedadid));
CREATE TABLE componente_sigade (id number(10) NOT NULL, nombre varchar2(2000) NOT NULL, codigo_presupuestario varchar2(45) NOT NULL, numero_componente number(10) NOT NULL, monto_componente number(15, 2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE componente_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE componente_usuario (componenteid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (componenteid, usuario));
CREATE TABLE cooperante (codigo number(5) NOT NULL, siglas varchar2(45), nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, ejercicio number(4) NOT NULL, PRIMARY KEY (codigo, ejercicio));
CREATE TABLE ctipo_propiedad (componente_tipoid number(10) NOT NULL, componente_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (componente_tipoid, componente_propiedadid));
CREATE TABLE dato_tipo (id number(10) NOT NULL, nombre varchar2(100) NOT NULL, descripcion varchar2(1000), PRIMARY KEY (id));
CREATE TABLE desembolso (id number(10) NOT NULL, fecha timestamp(0) NOT NULL, estado number(2) NOT NULL, monto number(15, 2) NOT NULL, tipo_cambio number(15, 4) NOT NULL, monto_moneda_origen number(11), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), proyectoid number(10) NOT NULL, desembolso_tipoid number(10) NOT NULL, tipo_monedaid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE desembolso_tipo (id number(10) NOT NULL, nombre varchar2(1000), descripcion varchar2(4000), estado number(2), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (id));
CREATE TABLE documento (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, extension varchar2(45) NOT NULL, id_tipo_objeto number(11) NOT NULL, id_objeto number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE ejecucion_estado (id number(11) NOT NULL, nombre varchar2(10) NOT NULL, descripcion varchar2(1000), PRIMARY KEY (id));
CREATE TABLE entidad (entidad number(10) NOT NULL, nombre varchar2(1000) NOT NULL, abreviatura varchar2(100), ejercicio number(4) NOT NULL, PRIMARY KEY (entidad));
CREATE TABLE estado (id number(10) NOT NULL, nombre varchar2(30) NOT NULL, valor number(2) NOT NULL);
CREATE TABLE estado_tabla (usuario varchar2(30) NOT NULL, tabla varchar2(50) NOT NULL, valores varchar2(1000) NOT NULL, PRIMARY KEY (usuario, tabla));
CREATE TABLE etiqueta (id number(2) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), proyecto varchar2(50) NOT NULL, color_principal varchar2(30) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE formulario (id number(10) NOT NULL, codigo varchar2(30) NOT NULL, descripcion varchar2(4000) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, formulario_tipoid number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE formulario_item (id number(10) NOT NULL, texto varchar2(4000) NOT NULL, formularioid number(10) NOT NULL, orden number(3) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizacion number(10), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, formulario_item_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE formulario_item_opcion (id number(10) NOT NULL, formulario_itemid number(10) NOT NULL, etiqueta varchar2(4000) NOT NULL, valor_entero number(4), valor_string varchar2(4000), valor_tiempo timestamp(0), valor_decimal number(15, 2), estado number(2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizacion number(11), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (id));
CREATE TABLE formulario_item_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), estado number(2), usuario_creo varchar2(30) NOT NULL, fecha_creacion timestamp(0) NOT NULL, usuario_actualizacion varchar2(30), fecha_actualizacion timestamp(0), dato_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE formulario_item_valor (formulario_itemid number(10) NOT NULL, objeto_formularioformularioid number(10) NOT NULL, objeto_formularioobjeto_tipoid number(2) NOT NULL, valor_entero number(10) NOT NULL, valor_string varchar2(4000), valor_tiempo timestamp(0), valor_decimal number(15, 2), proyectoid number(10) NOT NULL, componenteid number(10) NOT NULL, productoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), objeto_formularioobjeto_id number(10) NOT NULL, PRIMARY KEY (formulario_itemid, objeto_formularioformularioid, objeto_formularioobjeto_tipoid, objeto_formularioobjeto_id));
CREATE TABLE formulario_tipo (id number(2) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE hito (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, fecha timestamp(0) NOT NULL, proyectoid number(10) NOT NULL, hito_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE hito_resultado (id number(10) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), comentario varchar2(4000), hitoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE hito_tipo (id number(10) NOT NULL, nombre varchar2(1000), descripcion varchar2(4000), estado number(2) NOT NULL, dato_tipoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizacion varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (id));
CREATE TABLE interes_tipo (id number(10) NOT NULL, nombre varchar2(100) NOT NULL, descripcion varchar2(1000), PRIMARY KEY (id));
CREATE TABLE linea_base (id number(10) NOT NULL, nombre varchar2(100) NOT NULL, proyectoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), tipo_linea_base number(2) NOT NULL, sobreescribir number(2), PRIMARY KEY (id));
CREATE TABLE matriz_raci (id number(11) NOT NULL, proyectoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE meta (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2), meta_unidad_medidaid number(10) NOT NULL, dato_tipoid number(10) NOT NULL, objeto_id number(11), objeto_tipo number(11), meta_final_entero number(10), meta_final_string clob, meta_final_decimal number(15, 2), meta_final_fecha timestamp(0), PRIMARY KEY (id));
CREATE TABLE meta_avance (metaid number(10) NOT NULL, fecha timestamp(0) NOT NULL, usuario varchar2(30) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), estado number(2) NOT NULL, fecha_ingreso timestamp(0) NOT NULL);
CREATE TABLE meta_planificado (metaid number(10) NOT NULL, ejercicio number(4) NOT NULL, enero_entero number(10), enero_string clob, enero_decimal number(15, 2), enero_tiempo timestamp(0), febrero_entero number(10), febrero_string clob, febrero_decimal number(15, 2), febrero_tiempo timestamp(0), marzo_entero number(10), marzo_string clob, marzo_decimal number(15, 2), marzo_tiempo timestamp(0), abril_entero number(10), abril_string clob, abril_decimal number(15, 2), abril_tiempo timestamp(0), mayo_entero number(10), mayo_string clob, mayo_decimal number(15, 2), mayo_tiempo timestamp(0), junio_entero number(10), junio_string clob, junio_decimal number(15, 2), junio_tiempo timestamp(0), julio_entero number(10), julio_string clob, julio_decimal number(15, 2), julio_tiempo timestamp(0), agosto_entero number(10), agosto_string clob, agosto_decimal number(15, 2), agosto_tiempo timestamp(0), septiembre_entero number(10), septiembre_string clob, septiembre_decimal number(15, 2), septiembre_tiempo timestamp(0), octubre_entero number(10), octubre_string clob, octubre_decimal number(15, 2), octubre_tiempo timestamp(0), noviembre_entero number(10), noviembre_string clob, noviembre_decimal number(15, 2), noviembre_tiempo timestamp(0), diciembre_entero number(10), diciembre_string clob, diciembre_decimal number(15, 2), diciembre_tiempo timestamp(0), estado number(2) NOT NULL, usuario varchar2(30) NOT NULL, fecha_ingreso timestamp(0) NOT NULL, PRIMARY KEY (metaid, ejercicio));
CREATE TABLE meta_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE meta_unidad_medida (id number(10) NOT NULL, nombre varchar2(1000), descripcion varchar2(4000), simbolo varchar2(10), usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), estado number(2), PRIMARY KEY (id));
CREATE TABLE meta_valor (metaid number(10) NOT NULL, fecha timestamp(0) NOT NULL, usuario varchar2(30) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), PRIMARY KEY (metaid, fecha));
CREATE TABLE objeto_formulario (formularioid number(10) NOT NULL, objeto_tipo number(2) NOT NULL, objeto_id number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (formularioid, objeto_tipo, objeto_id));
CREATE TABLE objeto_riesgo (riesgoid number(10) NOT NULL, objeto_id number(11) NOT NULL, objeto_tipo number(11) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (riesgoid, objeto_id, objeto_tipo));
CREATE TABLE pago_planificado (id number(10) NOT NULL, fecha_pago timestamp(0) NOT NULL, pago number(15, 2) NOT NULL, objeto_id number(10) NOT NULL, objeto_tipo number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE pep_detalle (proyectoid number(10) NOT NULL, observaciones varchar2(4000), alertivos varchar2(4000), elaborado varchar2(100), aprobado varchar2(100), autoridad varchar2(100), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (proyectoid));
CREATE TABLE permiso (id number(11) NOT NULL, nombre varchar2(255) NOT NULL, descripcion varchar2(4000) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE plan_adquisicion (id number(11) NOT NULL, tipo_adquisicion number(11) NOT NULL, categoria_adquisicion number(11) NOT NULL, unidad_medida varchar2(30), cantidad number(11), total number(15, 2), precio_unitario number(15, 2), preparacion_doc_planificado timestamp(0), preparacion_doc_real timestamp(0), lanzamiento_evento_planificado timestamp(0), lanzamiento_evento_real timestamp(0), recepcion_ofertas_planificado timestamp(0), recepcion_ofertas_real timestamp(0), adjudicacion_planificado timestamp(0), adjudicacion_real timestamp(0), firma_contrato_planificado timestamp(0), firma_contrato_real timestamp(0), objeto_id number(11) NOT NULL, objeto_tipo number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2), bloqueado number(2), numero_contrato varchar2(45), monto_contrato number(15, 2) NOT NULL, nog number(8), tipo_revision number(1), PRIMARY KEY (id));
CREATE TABLE plan_adquisicion_pago (id number(11) NOT NULL, plan_adquisicionid number(11) NOT NULL, fecha_pago timestamp(0) NOT NULL, pago number(15, 2), descripcion varchar2(100) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE prestamo (id number(10) NOT NULL, fecha_corte timestamp(0), codigo_presupuestario number(12) NOT NULL, numero_prestamo varchar2(30) NOT NULL, destino varchar2(1000), sector_economico varchar2(1000), ueunidad_ejecutora number(10) NOT NULL, fecha_firma timestamp(0), autorizacion_tipoid number(10), numero_autorizacion varchar2(100), fecha_autorizacion timestamp(0), anios_plazo number(3), anios_gracia number(3), fecha_fin_ejecucion timestamp(0), perido_ejecucion number(3), interes_tipoid number(10), porcentaje_interes number(10, 5), porcentaje_comision_compra number(10, 5), tipo_monedaid number(10) NOT NULL, monto_contratado number(15, 2) NOT NULL, amortizado number(15, 2), por_amortizar number(15, 2), principal_anio number(15, 2), intereses_anio number(15, 2), comision_compromiso_anio number(15, 2), otros_gastos number(15, 2), principal_acumulado number(15, 2), intereses_acumulados number(15, 2), comision_compromiso_acumulado number(15, 2), otros_cargos_acumulados number(15, 2), presupuesto_asignado_func number(15, 2), presupuesto_asignado_inv number(15, 2), presupuesto_modificado_func number(15, 2), presupuesto_modificado_inv number(15, 2), presupuesto_vigente_func number(15, 2), presupuesto_vigente_inv number(15, 2), presupuesto_devengado_func number(15, 2), presupuesto_devengado_inv number(15, 2), presupuesto_pagado_func number(15, 2), presupuesto_pagado_inv number(15, 2), saldo_cuentas number(15, 2), desembolsado_real number(15, 2), ejecucion_estadoid number(10), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, proyecto_programa varchar2(100) NOT NULL, fecha_decreto timestamp(0) NOT NULL, fecha_suscripcion timestamp(0) NOT NULL, fecha_elegibilidad_ue timestamp(0) NOT NULL, fecha_cierre_origianl_ue timestamp(0) NOT NULL, fecha_cierre_actual_ue timestamp(0) NOT NULL, meses_prorroga_ue number(3) NOT NULL, plazo_ejecucion_ue number(3), monto_asignado_ue number(15, 2), desembolso_a_fecha_ue number(15, 2), monto_por_desembolsar_ue number(15, 2), fecha_vigencia timestamp(0) NOT NULL, monto_contratado_usd number(15, 2) NOT NULL, monto_contratado_qtz number(15, 2) NOT NULL, desembolso_a_fecha_usd number(15, 2), monto_por_desembolsar_usd number(15, 2) NOT NULL, monto_asignado_ue_usd number(15, 2), monto_asignado_ue_qtz number(15, 2), desembolso_a_fecha_ue_usd number(15, 2), monto_por_desembolsar_ue_usd number(15, 2), entidad number(10) NOT NULL, ejercicio number(4) NOT NULL, objetivo varchar2(4000), objetivo_especifico varchar2(4000), porcentaje_avance number(3) NOT NULL, cooperantecodigo number(5), cooperanteejercicio number(4), PRIMARY KEY (id));
CREATE TABLE prestamo_tipo (id number(11) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE prestamo_tipo_prestamo (prestamoId number(10) NOT NULL, tipoPrestamoId number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL);
CREATE TABLE prestamo_usuario (prestamoid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (prestamoid, usuario));
CREATE TABLE prodtipo_propiedad (producto_tipoid number(10) NOT NULL, producto_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (producto_tipoid, producto_propiedadid));
CREATE TABLE producto (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), componenteid number(10), subcomponenteid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), producto_tipoid number(10) NOT NULL, estado number(2), ueunidad_ejecutora number(10) NOT NULL, snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), latitud varchar2(30), longitud varchar2(30), peso number(3), costo number(15, 2), acumulacion_costoid number(11) NOT NULL, renglon number(4), ubicacion_geografica number(4), fecha_inicio timestamp(0), fecha_fin timestamp(0), duracion number(10) NOT NULL, duracion_dimension varchar2(1), orden number(10), treePath varchar2(1000), nivel number(4), ejercicio number(4) NOT NULL, entidad number(10), fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), inversion_nueva number(1), PRIMARY KEY (id));
CREATE TABLE producto_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), dato_tipoid number(10) NOT NULL, estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE producto_propiedad_valor (producto_propiedadid number(10) NOT NULL, productoid number(10) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (producto_propiedadid, productoid));
CREATE TABLE producto_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE producto_usuario (productoid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (productoid, usuario));
CREATE TABLE proyecto (id number(10) NOT NULL, nombre varchar2(2000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, proyecto_tipoid number(10) NOT NULL, ueunidad_ejecutora number(10) NOT NULL, snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), latitud varchar2(30), longitud varchar2(30), objetivo varchar2(4000), director_proyecto number(10), enunciado_alcance varchar2(4000), costo number(15, 2), acumulacion_costoid number(11) NOT NULL, objetivo_especifico varchar2(4000), vision_general varchar2(45), renglon number(4), ubicacion_geografica number(4), fecha_inicio timestamp(0), fecha_fin timestamp(0), duracion number(10) NOT NULL, duracion_dimension varchar2(1), orden number(10), treePath varchar2(1000), nivel number(4), ejercicio number(4) NOT NULL, entidad number(10), ejecucion_fisica_real number(3), proyecto_clase number(2) NOT NULL, project_cargado number(1), prestamoid number(10), observaciones varchar2(2000), coordinador number(1), fecha_elegibilidad timestamp(0), fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), congelado number(1), fecha_cierre timestamp(0), PRIMARY KEY (id));
CREATE TABLE proyecto_impacto (id number(11) NOT NULL, proyectoid number(10) NOT NULL, entidadentidad number(10) NOT NULL, impacto varchar2(1000) NOT NULL, estado number(2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), ejercicio number(4) NOT NULL, PRIMARY KEY (id));
CREATE TABLE proyecto_miembro (proyectoid number(10) NOT NULL, colaboradorid number(10) NOT NULL, estado number(2) NOT NULL, fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), PRIMARY KEY (proyectoid, colaboradorid));
CREATE TABLE proyecto_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), dato_tipoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE proyecto_propiedad_valor (proyectoid number(10) NOT NULL, proyecto_propiedadid number(10) NOT NULL, valor_string varchar2(4000), valor_entero number(10), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (proyectoid, proyecto_propiedadid));
CREATE TABLE proyecto_rol_colaborador (id number(10) NOT NULL, colaboradorid number(10) NOT NULL, proyectoid number(10) NOT NULL, rol_unidad_ejecutoraid number(10) NOT NULL, estado number(2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (id));
CREATE TABLE proyecto_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE proyecto_usuario (proyectoid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (proyectoid, usuario));
CREATE TABLE ptipo_propiedad (proyecto_tipoid number(10) NOT NULL, proyecto_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2), PRIMARY KEY (proyecto_tipoid, proyecto_propiedadid));
CREATE TABLE riesgo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), riesgo_tipoid number(10) NOT NULL, impacto number(3, 2) NOT NULL, probabilidad number(3, 2) NOT NULL, impacto_monto number(15, 2), impacto_tiempo number(15, 2), gatillo varchar2(1000), consecuencia varchar2(1000), solucion varchar2(1000), riesgos_segundarios varchar2(1000), ejecutado number(1) NOT NULL, fecha_ejecucion timestamp(0), resultado varchar2(1000), observaciones varchar2(1000), colaboradorid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE riesgo_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, dato_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE riesgo_propiedad_valor (riesgoid number(10) NOT NULL, riesgo_propiedadid number(10) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), estado number(2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (riesgoid, riesgo_propiedadid));
CREATE TABLE riesgo_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE rol (id number(10) NOT NULL, nombre varchar2(255) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE rol_permiso (rolid number(10) NOT NULL, permisoid number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (rolid, permisoid));
CREATE TABLE rol_unidad_ejecutora (id number(10) NOT NULL, nombre varchar2(500) NOT NULL, estado number(2) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), rol_predeterminado number(2), PRIMARY KEY (id));
CREATE TABLE rol_usuario_proyecto (rol number(11) NOT NULL, proyecto number(11) NOT NULL, usuario varchar2(30) NOT NULL, PRIMARY KEY (rol, proyecto, usuario));
CREATE TABLE rtipo_propiedad (riesgo_tipoid number(10) NOT NULL, riesgo_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (riesgo_tipoid, riesgo_propiedadid));
CREATE TABLE sctipo_propiedad (subcomponente_tipoid number(10) NOT NULL, subcomponente_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (subcomponente_tipoid, subcomponente_propiedadid));
CREATE TABLE subcomponente (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), componenteid number(10) NOT NULL, subcomponente_tipoid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, ueunidad_ejecutora number(10), snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), latitud varchar2(30), longitud varchar2(30), costo number(15, 2), acumulacion_costoid number(11) NOT NULL, renglon number(4), ubicacion_geografica number(4), fecha_inicio timestamp(0), fecha_fin timestamp(0), duracion number(10) NOT NULL, duracion_dimension varchar2(1), orden number(10), treePath varchar2(1000), nivel number(4), entidad number(10), ejercicio number(4), fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), inversion_nueva number(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subcomponente_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), dato_tipoid number(10) NOT NULL, estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subcomponente_propiedad_valor (subcomponenteid number(10) NOT NULL, subcomponente_propiedadid number(10) NOT NULL, valor_string varchar2(4000), valor_entero number(10), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (subcomponenteid, subcomponente_propiedadid));
CREATE TABLE subcomponente_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subcomponente_usuario (subcomponenteid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0), fecha_actualizacion timestamp(0), PRIMARY KEY (subcomponenteid, usuario));
CREATE TABLE subprodtipo_propiedad (subproducto_tipoid number(10) NOT NULL, subproducto_propiedadid number(10) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (subproducto_tipoid, subproducto_propiedadid));
CREATE TABLE subproducto (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(4000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, snip number(10), programa number(4), subprograma number(4), proyecto number(4), actividad number(4), obra number(4), productoid number(10) NOT NULL, subproducto_tipoid number(10) NOT NULL, ueunidad_ejecutora number(10) NOT NULL, latitud varchar2(30), longitud varchar2(30), costo number(15, 2), acumulacion_costoid number(11) NOT NULL, renglon number(4), ubicacion_geografica number(4), fecha_inicio timestamp(0) NOT NULL, fecha_fin timestamp(0), duracion number(10) NOT NULL, duracion_dimension varchar2(1), orden number(10), treePath varchar2(1000), nivel number(4), ejercicio number(4) NOT NULL, entidad number(10), fecha_inicio_real timestamp(0), fecha_fin_real timestamp(0), inversion_nueva number(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subproducto_propiedad (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, dato_tipoid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subproducto_propiedad_valor (subproductoid number(10) NOT NULL, subproducto_propiedadid number(10) NOT NULL, valor_entero number(10), valor_string varchar2(4000), valor_decimal number(15, 2), valor_tiempo timestamp(0), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (subproductoid, subproducto_propiedadid));
CREATE TABLE subproducto_tipo (id number(10) NOT NULL, nombre varchar2(1000) NOT NULL, descripcion varchar2(2000), usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE subproducto_usuario (subproductoid number(10) NOT NULL, usuario varchar2(30) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), PRIMARY KEY (subproductoid, usuario));
CREATE TABLE tipo_adquisicion (id number(11) NOT NULL, cooperantecodigo number(5) NOT NULL, cooperanteejercicio number(4), nombre varchar2(1000) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, convenio_cdirecta number(1), PRIMARY KEY (id));
CREATE TABLE tipo_moneda (id number(10) NOT NULL, nombre varchar2(1000), simbolo varchar2(5), PRIMARY KEY (id));
CREATE TABLE unidad_ejecutora (unidad_ejecutora number(10) NOT NULL, nombre varchar2(1000) NOT NULL, entidadentidad number(10) NOT NULL, ejercicio number(4) NOT NULL, PRIMARY KEY (unidad_ejecutora, entidadentidad, ejercicio));
CREATE TABLE unidad_medida (id number(11) NOT NULL, nombre varchar2(100) NOT NULL, descripcion varchar2(100), usuario_creo varchar2(30) NOT NULL, usuario_actualizacion varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (id));
CREATE TABLE usuario (usuario varchar2(30) NOT NULL, password varchar2(255) NOT NULL, salt varchar2(255) NOT NULL, email varchar2(255) NOT NULL, usuario_creo varchar2(30), usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, sistema_usuario number(2) NOT NULL, PRIMARY KEY (usuario));
CREATE TABLE usuario_log (usuario varchar2(30), fecha timestamp(0));
CREATE TABLE usuario_permiso (usuariousuario varchar2(30) NOT NULL, permisoid number(11) NOT NULL, usuario_creo varchar2(30) NOT NULL, usuario_actualizo varchar2(30), fecha_creacion timestamp(0) NOT NULL, fecha_actualizacion timestamp(0), estado number(2) NOT NULL, PRIMARY KEY (usuariousuario, permisoid));
ALTER TABLE formulario_item ADD CONSTRAINT FKformulario123316 FOREIGN KEY (formulario_item_tipoid) REFERENCES formulario_item_tipo (id);
ALTER TABLE prodtipo_propiedad ADD CONSTRAINT FKprodtipo_p470266 FOREIGN KEY (producto_tipoid) REFERENCES producto_tipo (id);
ALTER TABLE prodtipo_propiedad ADD CONSTRAINT FKprodtipo_p326363 FOREIGN KEY (producto_propiedadid) REFERENCES producto_propiedad (id);
ALTER TABLE producto_propiedad ADD CONSTRAINT FKproducto_p535852 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE producto_propiedad_valor ADD CONSTRAINT FKproducto_p555801 FOREIGN KEY (producto_propiedadid) REFERENCES producto_propiedad (id);
ALTER TABLE producto_propiedad_valor ADD CONSTRAINT FKproducto_p148049 FOREIGN KEY (productoid) REFERENCES producto (id);
ALTER TABLE meta ADD CONSTRAINT FKmeta832527 FOREIGN KEY (meta_unidad_medidaid) REFERENCES meta_unidad_medida (id);
ALTER TABLE meta_valor ADD CONSTRAINT FKmeta_valor168661 FOREIGN KEY (metaid) REFERENCES meta (id);
ALTER TABLE hito ADD CONSTRAINT FKhito29799 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE hito ADD CONSTRAINT FKhito59625 FOREIGN KEY (hito_tipoid) REFERENCES hito_tipo (id);
ALTER TABLE hito_resultado ADD CONSTRAINT FKhito_resul737850 FOREIGN KEY (hitoid) REFERENCES hito (id);
ALTER TABLE formulario_item ADD CONSTRAINT FKformulario449783 FOREIGN KEY (formularioid) REFERENCES formulario (id);
ALTER TABLE objeto_formulario ADD CONSTRAINT FKobjeto_for155797 FOREIGN KEY (formularioid) REFERENCES formulario (id);
ALTER TABLE formulario_item_valor ADD CONSTRAINT FKformulario508490 FOREIGN KEY (formulario_itemid) REFERENCES formulario_item (id);
ALTER TABLE desembolso ADD CONSTRAINT FKdesembolso151185 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE desembolso ADD CONSTRAINT FKdesembolso941697 FOREIGN KEY (desembolso_tipoid) REFERENCES desembolso_tipo (id);
ALTER TABLE riesgo_propiedad_valor ADD CONSTRAINT FKriesgo_pro389855 FOREIGN KEY (riesgoid) REFERENCES riesgo (id);
ALTER TABLE riesgo_propiedad_valor ADD CONSTRAINT FKriesgo_pro900192 FOREIGN KEY (riesgo_propiedadid) REFERENCES riesgo_propiedad (id);
ALTER TABLE riesgo ADD CONSTRAINT FKriesgo901387 FOREIGN KEY (riesgo_tipoid) REFERENCES riesgo_tipo (id);
ALTER TABLE rtipo_propiedad ADD CONSTRAINT FKrtipo_prop489076 FOREIGN KEY (riesgo_tipoid) REFERENCES riesgo_tipo (id);
ALTER TABLE rtipo_propiedad ADD CONSTRAINT FKrtipo_prop994938 FOREIGN KEY (riesgo_propiedadid) REFERENCES riesgo_propiedad (id);
ALTER TABLE colaborador ADD CONSTRAINT FKcolaborado783156 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE colaborador ADD CONSTRAINT FKcolaborado544592 FOREIGN KEY (usuariousuario) REFERENCES usuario (usuario);
ALTER TABLE usuario_permiso ADD CONSTRAINT FKusuario_pe242169 FOREIGN KEY (usuariousuario) REFERENCES usuario (usuario);
ALTER TABLE usuario_permiso ADD CONSTRAINT FKusuario_pe101130 FOREIGN KEY (permisoid) REFERENCES permiso (id);
ALTER TABLE rol_permiso ADD CONSTRAINT FKrol_permis670833 FOREIGN KEY (rolid) REFERENCES rol (id);
ALTER TABLE rol_permiso ADD CONSTRAINT FKrol_permis272334 FOREIGN KEY (permisoid) REFERENCES permiso (id);
ALTER TABLE proyecto ADD CONSTRAINT FKproyecto829715 FOREIGN KEY (proyecto_tipoid) REFERENCES proyecto_tipo (id);
ALTER TABLE ptipo_propiedad ADD CONSTRAINT FKptipo_prop684655 FOREIGN KEY (proyecto_tipoid) REFERENCES proyecto_tipo (id);
ALTER TABLE ptipo_propiedad ADD CONSTRAINT FKptipo_prop536620 FOREIGN KEY (proyecto_propiedadid) REFERENCES proyecto_propiedad (id);
ALTER TABLE proyecto_propiedad_valor ADD CONSTRAINT FKproyecto_p36526 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE proyecto_propiedad_valor ADD CONSTRAINT FKproyecto_p627062 FOREIGN KEY (proyecto_propiedadid) REFERENCES proyecto_propiedad (id);
ALTER TABLE proyecto_propiedad ADD CONSTRAINT FKproyecto_p357270 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE unidad_ejecutora ADD CONSTRAINT FKunidad_eje520092 FOREIGN KEY (entidadentidad) REFERENCES entidad (entidad);
ALTER TABLE proyecto ADD CONSTRAINT FKproyecto583943 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE componente ADD CONSTRAINT FKcomponente380208 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE componente ADD CONSTRAINT FKcomponente53483 FOREIGN KEY (componente_tipoid) REFERENCES componente_tipo (id);
ALTER TABLE componente_propiedad ADD CONSTRAINT FKcomponente26853 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE ctipo_propiedad ADD CONSTRAINT FKctipo_prop358116 FOREIGN KEY (componente_tipoid) REFERENCES componente_tipo (id);
ALTER TABLE ctipo_propiedad ADD CONSTRAINT FKctipo_prop74576 FOREIGN KEY (componente_propiedadid) REFERENCES componente_propiedad (id);
ALTER TABLE componente_propiedad_valor ADD CONSTRAINT FKcomponente747047 FOREIGN KEY (componenteid) REFERENCES componente (id);
ALTER TABLE componente_propiedad_valor ADD CONSTRAINT FKcomponente278188 FOREIGN KEY (componente_propiedadid) REFERENCES componente_propiedad (id);
ALTER TABLE producto ADD CONSTRAINT FKproducto332920 FOREIGN KEY (componenteid) REFERENCES componente (id);
ALTER TABLE producto ADD CONSTRAINT FKproducto619237 FOREIGN KEY (producto_tipoid) REFERENCES producto_tipo (id);
ALTER TABLE actividad ADD CONSTRAINT FKactividad818457 FOREIGN KEY (actividad_tipoid) REFERENCES actividad_tipo (id);
ALTER TABLE actividad_propiedad ADD CONSTRAINT FKactividad_557567 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE atipo_propiedad ADD CONSTRAINT FKatipo_prop395442 FOREIGN KEY (actividad_tipoid) REFERENCES actividad_tipo (id);
ALTER TABLE atipo_propiedad ADD CONSTRAINT FKatipo_prop264327 FOREIGN KEY (actividad_propiedadid) REFERENCES actividad_propiedad (id);
ALTER TABLE actividad_propiedad_valor ADD CONSTRAINT FKactividad_548986 FOREIGN KEY (actividadid) REFERENCES actividad (id);
ALTER TABLE actividad_propiedad_valor ADD CONSTRAINT FKactividad_3878 FOREIGN KEY (actividad_propiedadid) REFERENCES actividad_propiedad (id);
ALTER TABLE hito_tipo ADD CONSTRAINT FKhito_tipo850233 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE riesgo_propiedad ADD CONSTRAINT FKriesgo_pro642830 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE formulario ADD CONSTRAINT FKformulario341300 FOREIGN KEY (formulario_tipoid) REFERENCES formulario_tipo (id);
ALTER TABLE formulario_item_opcion ADD CONSTRAINT FKformulario718877 FOREIGN KEY (formulario_itemid) REFERENCES formulario_item (id);
ALTER TABLE formulario_item_tipo ADD CONSTRAINT FKformulario967906 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE formulario_item_valor ADD CONSTRAINT FKformulario833430 FOREIGN KEY (objeto_formularioformularioid, objeto_formularioobjeto_tipoid, objeto_formularioobjeto_id) REFERENCES objeto_formulario (formularioid, objeto_tipo, objeto_id);
ALTER TABLE objeto_riesgo ADD CONSTRAINT FKobjeto_rie619314 FOREIGN KEY (riesgoid) REFERENCES riesgo (id);
ALTER TABLE componente ADD CONSTRAINT FKcomponente982243 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE producto ADD CONSTRAINT FKproducto666639 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE proyecto_usuario ADD CONSTRAINT FKproyecto_u77327 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE producto_usuario ADD CONSTRAINT FKproducto_u785635 FOREIGN KEY (productoid) REFERENCES producto (id);
ALTER TABLE componente_usuario ADD CONSTRAINT FKcomponente114298 FOREIGN KEY (componenteid) REFERENCES componente (id);
ALTER TABLE actividad_usuario ADD CONSTRAINT FKactividad_980179 FOREIGN KEY (actividadid) REFERENCES actividad (id);
ALTER TABLE meta ADD CONSTRAINT FKmeta336167 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE subproducto ADD CONSTRAINT FKsubproduct375225 FOREIGN KEY (productoid) REFERENCES producto (id);
ALTER TABLE subproducto_usuario ADD CONSTRAINT FKsubproduct290099 FOREIGN KEY (subproductoid) REFERENCES subproducto (id);
ALTER TABLE subproducto_propiedad ADD CONSTRAINT FKsubproduct396653 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE subproducto ADD CONSTRAINT FKsubproduct661539 FOREIGN KEY (subproducto_tipoid) REFERENCES subproducto_tipo (id);
ALTER TABLE subprodtipo_propiedad ADD CONSTRAINT FKsubprodtip230372 FOREIGN KEY (subproducto_tipoid) REFERENCES subproducto_tipo (id);
ALTER TABLE subprodtipo_propiedad ADD CONSTRAINT FKsubprodtip762195 FOREIGN KEY (subproducto_propiedadid) REFERENCES subproducto_propiedad (id);
ALTER TABLE subproducto_propiedad_valor ADD CONSTRAINT FKsubproduct923614 FOREIGN KEY (subproductoid) REFERENCES subproducto (id);
ALTER TABLE subproducto_propiedad_valor ADD CONSTRAINT FKsubproduct665739 FOREIGN KEY (subproducto_propiedadid) REFERENCES subproducto_propiedad (id);
ALTER TABLE desembolso ADD CONSTRAINT FKdesembolso995959 FOREIGN KEY (tipo_monedaid) REFERENCES tipo_moneda (id);
ALTER TABLE subproducto ADD CONSTRAINT FKsubproduct434325 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE actividad ADD CONSTRAINT FKactividad487061 FOREIGN KEY (acumulacion_costo) REFERENCES acumulacion_costo (id);
ALTER TABLE matriz_raci ADD CONSTRAINT FKmatriz_rac867859 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE asignacion_raci ADD CONSTRAINT FKasignacion315938 FOREIGN KEY (matriz_raciid) REFERENCES matriz_raci (id);
ALTER TABLE asignacion_raci ADD CONSTRAINT FKasignacion469415 FOREIGN KEY (colaboradorid) REFERENCES colaborador (id);
ALTER TABLE componente ADD CONSTRAINT FKcomponente13467 FOREIGN KEY (acumulacion_costoid) REFERENCES acumulacion_costo (id);
ALTER TABLE componente ADD CONSTRAINT FKcomponente564231 FOREIGN KEY (componente_sigadeid) REFERENCES componente_sigade (id);
ALTER TABLE meta_avance ADD CONSTRAINT FKmeta_avanc656956 FOREIGN KEY (metaid) REFERENCES meta (id);
ALTER TABLE meta_planificado ADD CONSTRAINT FKmeta_plani695742 FOREIGN KEY (metaid) REFERENCES meta (id);
ALTER TABLE riesgo ADD CONSTRAINT FKriesgo148789 FOREIGN KEY (colaboradorid) REFERENCES colaborador (id);
ALTER TABLE tipo_adquisicion ADD CONSTRAINT FKtipo_adqui479783 FOREIGN KEY (cooperantecodigo, cooperanteejercicio) REFERENCES cooperante (codigo, ejercicio);
ALTER TABLE plan_adquisicion ADD CONSTRAINT FKplan_adqui169923 FOREIGN KEY (tipo_adquisicion) REFERENCES tipo_adquisicion (id);
ALTER TABLE plan_adquisicion ADD CONSTRAINT FKplan_adqui651573 FOREIGN KEY (categoria_adquisicion) REFERENCES categoria_adquisicion (id);
ALTER TABLE plan_adquisicion_pago ADD CONSTRAINT FKplan_adqui689845 FOREIGN KEY (plan_adquisicionid) REFERENCES plan_adquisicion (id);
ALTER TABLE prestamo ADD CONSTRAINT FKprestamo230739 FOREIGN KEY (tipo_monedaid) REFERENCES tipo_moneda (id);
ALTER TABLE prestamo ADD CONSTRAINT FKprestamo226688 FOREIGN KEY (cooperantecodigo, cooperanteejercicio) REFERENCES cooperante (codigo, ejercicio);
ALTER TABLE prestamo ADD CONSTRAINT FKprestamo195742 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE prestamo_tipo_prestamo ADD CONSTRAINT FKprestamo_t867745 FOREIGN KEY (prestamoId) REFERENCES prestamo (id);
ALTER TABLE prestamo_tipo_prestamo ADD CONSTRAINT FKprestamo_t857477 FOREIGN KEY (tipoPrestamoId) REFERENCES prestamo_tipo (id);
ALTER TABLE prestamo_usuario ADD CONSTRAINT FKprestamo_u532370 FOREIGN KEY (prestamoid) REFERENCES prestamo (id);
ALTER TABLE subcomponente ADD CONSTRAINT FKsubcompone580264 FOREIGN KEY (componenteid) REFERENCES componente (id);
ALTER TABLE subcomponente_propiedad ADD CONSTRAINT FKsubcompone106168 FOREIGN KEY (dato_tipoid) REFERENCES dato_tipo (id);
ALTER TABLE subcomponente_propiedad_valor ADD CONSTRAINT FKsubcompone565989 FOREIGN KEY (subcomponenteid) REFERENCES subcomponente (id);
ALTER TABLE subcomponente_propiedad_valor ADD CONSTRAINT FKsubcompone320311 FOREIGN KEY (subcomponente_propiedadid) REFERENCES subcomponente_propiedad (id);
ALTER TABLE subcomponente_usuario ADD CONSTRAINT FKsubcompone858957 FOREIGN KEY (subcomponenteid) REFERENCES subcomponente (id);
ALTER TABLE subcomponente ADD CONSTRAINT FKsubcompone125716 FOREIGN KEY (subcomponente_tipoid) REFERENCES subcomponente_tipo (id);
ALTER TABLE subcomponente ADD CONSTRAINT FKsubcompone608233 FOREIGN KEY (ueunidad_ejecutora, entidad, ejercicio) REFERENCES unidad_ejecutora (unidad_ejecutora, entidadentidad, ejercicio);
ALTER TABLE subcomponente ADD CONSTRAINT FKsubcompone360543 FOREIGN KEY (acumulacion_costoid) REFERENCES acumulacion_costo (id);
ALTER TABLE producto ADD CONSTRAINT FKproducto522529 FOREIGN KEY (subcomponenteid) REFERENCES subcomponente (id);
ALTER TABLE producto ADD CONSTRAINT FKproducto697862 FOREIGN KEY (acumulacion_costoid) REFERENCES acumulacion_costo (id);
ALTER TABLE proyecto ADD CONSTRAINT FKproyecto615166 FOREIGN KEY (acumulacion_costoid) REFERENCES acumulacion_costo (id);
ALTER TABLE proyecto ADD CONSTRAINT FKproyecto314414 FOREIGN KEY (prestamoid) REFERENCES prestamo (id);
ALTER TABLE proyecto_impacto ADD CONSTRAINT FKproyecto_i375862 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE proyecto_impacto ADD CONSTRAINT FKproyecto_i403069 FOREIGN KEY (entidadentidad) REFERENCES entidad (entidad);
ALTER TABLE proyecto_miembro ADD CONSTRAINT FKproyecto_m103555 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE proyecto_miembro ADD CONSTRAINT FKproyecto_m578022 FOREIGN KEY (colaboradorid) REFERENCES colaborador (id);
ALTER TABLE proyecto_rol_colaborador ADD CONSTRAINT FKproyecto_r615779 FOREIGN KEY (colaboradorid) REFERENCES colaborador (id);
ALTER TABLE proyecto_rol_colaborador ADD CONSTRAINT FKproyecto_r90247 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE proyecto_rol_colaborador ADD CONSTRAINT FKproyecto_r635719 FOREIGN KEY (rol_unidad_ejecutoraid) REFERENCES rol_unidad_ejecutora (id);
ALTER TABLE sctipo_propiedad ADD CONSTRAINT FKsctipo_pro414121 FOREIGN KEY (subcomponente_tipoid) REFERENCES subcomponente (id);
ALTER TABLE sctipo_propiedad ADD CONSTRAINT FKsctipo_pro693940 FOREIGN KEY (subcomponente_propiedadid) REFERENCES subcomponente_propiedad (id);
ALTER TABLE subproducto ADD CONSTRAINT FKsubproduct568488 FOREIGN KEY (acumulacion_costoid) REFERENCES acumulacion_costo (id);
ALTER TABLE prestamo_usuario ADD CONSTRAINT FKprestamo_u597628 FOREIGN KEY (usuario) REFERENCES usuario (usuario);
ALTER TABLE pep_detalle ADD CONSTRAINT FKpep_detall715338 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
ALTER TABLE linea_base ADD CONSTRAINT FKlinea_base993100 FOREIGN KEY (proyectoid) REFERENCES proyecto (id);
