using System;
using FluentValidation;
using Newtonsoft.Json.Linq;
using Utilities;

namespace SSubproductoTipo.Controllers
{
    /// <summary>
    /// A class which represents the SubproductoTipoValidator.
	/// Generated by SIPRO TEAM. May 2018. 
    /// </summary>

	public class SubproductoTipoValidator : AbstractValidator<JObject>
	{
		public SubproductoTipoValidator() 
		{
			//RuleFor(subproducto_tipo => subproducto_tipo["id"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'id' to type " + typeof(Int32));
			RuleFor(subproducto_tipo => subproducto_tipo["nombre"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'nombre' to type " + typeof(String)).MaximumLength(1000);
			RuleFor(subproducto_tipo => subproducto_tipo["descripcion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'descripcion' to type " + typeof(String)).MaximumLength(2000);
			//RuleFor(subproducto_tipo => subproducto_tipo["usuarioCreo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioCreo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(subproducto_tipo => subproducto_tipo["usuarioActualizo"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(String)); }).WithMessage("Error when trying to parse the property 'usuarioActualizo' to type " + typeof(String)).MaximumLength(30);
			//RuleFor(subproducto_tipo => subproducto_tipo["fechaCreacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaCreacion' to type " + typeof(DateTime));
			//RuleFor(subproducto_tipo => subproducto_tipo["fechaActualizacion"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(DateTime)); }).WithMessage("Error when trying to parse the property 'fechaActualizacion' to type " + typeof(DateTime));
			//RuleFor(subproducto_tipo => subproducto_tipo["estado"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).NotEmpty().Must(subproducto_tipo => { return GenericValidatorType.ValidateType(subproducto_tipo, typeof(Int32)); }).WithMessage("Error when trying to parse the property 'estado' to type " + typeof(Int32));
			
		}
	}
}
